allowBuilds:
  '@biomejs/biome': set this to true or false
  core-js: true
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "esbuild"
  - "sharp"
