// Per-language override lookup for app descriptions, app categories and
// national emergency contacts. Dictionaries are generated by
// scripts/translate-apps-emergency.mjs into src/data/apps/overrides-<lang>.ts
// and src/data/emergency/overrides-<lang>.ts.
// Eager glob: missing files simply produce no entries (no build break).
const APP_OVERRIDE_MODULES = import.meta.glob(
  "/src/data/apps/overrides-*.ts",
  { eager: true },
) as Record<string, Record<string, unknown>>;
const EMERGENCY_OVERRIDE_MODULES = import.meta.glob(
  "/src/data/emergency/overrides-*.ts",
  { eager: true },
) as Record<string, Record<string, unknown>>;

function extractMap(mod: Record<string, unknown>): Record<string, string> | undefined {
  for (const value of Object.values(mod)) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      return value as Record<string, string>;
    }
  }
  return undefined;
}

function buildRegistry(modules: Record<string, Record<string, unknown>>): Record<string, Record<string, string>> {
  const registry: Record<string, Record<string, string>> = {};
  for (const [file, mod] of Object.entries(modules)) {
    const match = /overrides-([\w-]+)\.ts$/.exec(file);
    if (match) {
      const map = extractMap(mod);
      if (map) registry[match[1]] = map;
    }
  }
  return registry;
}

const APP_OVERRIDES = buildRegistry(APP_OVERRIDE_MODULES);
const EMERGENCY_OVERRIDES = buildRegistry(EMERGENCY_OVERRIDE_MODULES);

/** Look up an app description / category label translation (key: "app:<id>" | "cat:<category>"). */
export function getAppOverride(lang: string | undefined, key: string): string | undefined {
  return lang ? APP_OVERRIDES[lang]?.[key] : undefined;
}

/** Look up a national emergency contact translation (key: "ename:<phone>" | "edesc:<phone>"). */
export function getEmergencyOverride(lang: string | undefined, key: string): string | undefined {
  return lang ? EMERGENCY_OVERRIDES[lang]?.[key] : undefined;
}
