const STORAGE_KEY = "chinaconnect-itineraries";
const MAX_ITINERARIES = 50;

export interface ItineraryStorageItem {
  id: string;
  name: string;
  destination: string;
  days: number;
  createdAt: string;
  updatedAt: string;
  summary?: {
    destination: string;
    totalDays: number;
    bestSeason: string;
    estimatedTotalCost: number;
    currency: string;
    costBreakdown: Record<string, number>;
    topHighlights: string[];
    travelTips: string[];
  };
  data?: {
    summary?: ItineraryStorageItem["summary"];
    dailyItinerary: unknown[];
    practicalInfo?: unknown[];
  };
  shareCode?: string;
}

function generateId(): string {
  return `itin_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function loadAll(): ItineraryStorageItem[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function saveAll(items: ItineraryStorageItem[]): void {
  // Keep only MAX_ITINERARIES most recent
  const trimmed = items.slice(-MAX_ITINERARIES);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(trimmed));
}

/**
 * Get all saved itineraries (metadata only)
 */
export function getItineraryList(): ItineraryStorageItem[] {
  return loadAll().map((item) => ({
    id: item.id,
    name: item.name,
    destination: item.destination,
    days: item.days,
    createdAt: item.createdAt,
    updatedAt: item.updatedAt,
    summary: item.summary,
    shareCode: item.shareCode,
  }));
}

/**
 * Get a single itinerary by ID
 */
export function getItinerary(id: string): ItineraryStorageItem | null {
  const items = loadAll();
  return items.find((item) => item.id === id) || null;
}

/**
 * Save an itinerary (create or update)
 */
export function saveItinerary(itinerary: Partial<ItineraryStorageItem>): ItineraryStorageItem {
  const items = loadAll();
  const now = new Date().toISOString();

  if (itinerary.id && !itinerary.id.startsWith("temp_")) {
    // Update existing
    const idx = items.findIndex((item) => item.id === itinerary.id);
    if (idx >= 0) {
      items[idx] = { ...items[idx], ...itinerary, updatedAt: now };
      saveAll(items);
      return items[idx];
    }
  }

  // Create new
  const newItem: ItineraryStorageItem = {
    id: generateId(),
    name: itinerary.name || "Unnamed Itinerary",
    destination: itinerary.destination || "",
    days: itinerary.days || 1,
    createdAt: now,
    updatedAt: now,
    summary: itinerary.summary,
    data: itinerary.data,
    shareCode: itinerary.shareCode,
  };

  items.push(newItem);
  saveAll(items);
  return newItem;
}

/**
 * Delete an itinerary by ID
 */
export function deleteItinerary(id: string): boolean {
  const items = loadAll();
  const idx = items.findIndex((item) => item.id === id);
  if (idx < 0) return false;

  items.splice(idx, 1);
  saveAll(items);
  return true;
}

/**
 * Clear all itineraries
 */
export function clearAllItineraries(): void {
  localStorage.removeItem(STORAGE_KEY);
}

/**
 * Generate a share code for an itinerary
 */
export function generateShareCode(id: string): string | null {
  const items = loadAll();
  const idx = items.findIndex((item) => item.id === id);
  if (idx < 0) return null;

  const code = Math.random().toString(36).slice(2, 8).toUpperCase();
  items[idx].shareCode = code;
  items[idx].updatedAt = new Date().toISOString();
  saveAll(items);
  return code;
}

/**
 * Get share link for a share code
 */
export function getShareLink(shareCode: string): string {
  if (typeof window === "undefined") return "";
  return `${window.location.origin}/ai?share=${shareCode}`;
}

/**
 * Export itinerary as text or JSON
 */
export function exportItinerary(id: string, format: "text" | "json"): string {
  const item = getItinerary(id);
  if (!item) return "";

  if (format === "json") {
    return JSON.stringify(item, null, 2);
  }

  const lines: string[] = [];
  lines.push(`# ${item.name}`);
  lines.push(`Destination: ${item.destination}`);
  lines.push(`Duration: ${item.days} days`);
  lines.push(`Created: ${new Date(item.createdAt).toLocaleDateString()}`);
  lines.push("");

  if (item.summary?.topHighlights?.length) {
    lines.push("## Highlights");
    item.summary.topHighlights.forEach((h) => lines.push(`- ${h}`));
    lines.push("");
  }

  if (item.summary?.estimatedTotalCost) {
    lines.push(
      `## Estimated Cost: ${item.summary.estimatedTotalCost} ${item.summary.currency || "CNY"}`,
    );
    lines.push("");
  }

  lines.push("Generated by ChinaConnect AI");
  return lines.join("\n");
}

/**
 * Create a temporary itinerary before saving
 */
export function createTempItinerary(data: Partial<ItineraryStorageItem>): ItineraryStorageItem {
  const now = new Date().toISOString();
  return {
    id: `temp_${Date.now()}`,
    name: data.name || "Untitled Trip",
    destination: data.destination || "",
    days: data.days || 1,
    createdAt: now,
    updatedAt: now,
    summary: data.summary,
    data: data.data,
  };
}

/**
 * Convert temporary itinerary to permanent
 */
export function promoteTempItinerary(tempId: string, _name: string): ItineraryStorageItem | null {
  const items = loadAll();
  const idx = items.findIndex((item) => item.id === tempId);
  if (idx >= 0) {
    // Already saved
    return items[idx];
  }

  // Promote from a partial object (not yet in storage)
  return null;
}
