/**
 * Auth UI strings (12 languages) shared by LoginPage / ResetPasswordPage.
 * Self-contained so the auth flow never depends on the huge translations.ts
 * dictionary being fully covered for every form label.
 */

export type AuthLang = "en" | "ja" | "ko" | "zh-CN" | "zh-TW" | "th" | "vi" | "ru" | "fr" | "de" | "ar" | "fa";

export const AUTH_LANGS: AuthLang[] = ["en","ja","ko","zh-CN","zh-TW","th","vi","ru","fr","de","ar","fa"];

type AuthKey = "profileUserNotFound" | "profileNotFoundDesc" | "profileEdit" | "profileDisplayName" | "profileBio" | "profileNationality" | "profileNationalityPlaceholder" | "profileCancel" | "profileSave" | "profilePosts" | "profileCheckins" | "profileLikesReceived" | "profileBestAnswers" | "profileMemberSince" | "profileAnonymous" | "profileSignInRequired" | "profileSignInRequiredDesc" | "profileUpdateSuccess" | "profileUpdateError" | "callbackSigningYouIn" | "callbackErrorTitle" | "callbackErrorDesc" | "callbackUnexpected" | "callbackBackToSignIn" | "tagline" | "tabSignIn" | "tabRegister" | "magicLinkBanner" | "forgotBanner" | "checkEmail" | "magicSentDesc" | "resetSentDesc" | "errorTitle" | "oauthUnavailable" | "displayNameLabel" | "displayNamePlaceholder" | "emailLabel" | "emailPlaceholder" | "passwordLabel" | "confirmEmailLabel" | "passwordPlaceholder" | "confirmEmailPlaceholder" | "processing" | "submitSignIn" | "submitRegister" | "submitMagicLink" | "submitReset" | "orContinueWith" | "demoActive" | "tryDemo" | "noAccount" | "signUp" | "magicLink" | "forgotPassword" | "haveAccount" | "signIn" | "backToSignIn" | "agreeTerms" | "terms" | "privacy" | "redirecting" | "providerSetup" | "oauthFailed" | "resetTitle" | "newPasswordLabel" | "newPasswordPlaceholder" | "confirmPasswordLabel" | "resetSubmit" | "resetDone" | "resetInvalid" | "resetLinkToLogin" | "updateFailed" | "resetPageTitle" | "otpSentDesc" | "otpCodeLabel" | "otpCodePlaceholder" | "verifyCode" | "resendCode" | "invalidCode";

const AUTH_STRINGS: Record<AuthKey, Record<AuthLang, string>> = {
  "tagline": {
    "en": "Your AI-powered China travel companion",
    "ja": "AIを活用した中国旅行のパートナー",
    "ko": "AI 기반 중국 여행 동반자",
    "zh-CN": "您的人工智能中国旅行助手",
    "zh-TW": "您的人工智慧中國旅遊助手",
    "th": "เพื่อนร่วมเดินทางจีนด้วย AI ของคุณ",
    "vi": "Người bạn đồng hành du lịch Trung Quốc bằng AI của bạn",
    "ru": "Ваш AI-компаньон для путешествий по Китаю",
    "fr": "Votre compagnon de voyage en Chine propulsé par l'IA",
    "de": "Ihr KI-Reisebegleiter für China",
    "ar": "رفيقك الذكي للسفر في الصين",
    "fa": "همراه هوشمند سفر شما به چین",
  },
  "tabSignIn": {
    "en": "Sign In",
    "ja": "ログイン",
    "ko": "로그인",
    "zh-CN": "登录",
    "zh-TW": "登入",
    "th": "เข้าสู่ระบบ",
    "vi": "Đăng nhập",
    "ru": "Войти",
    "fr": "Connexion",
    "de": "Anmelden",
    "ar": "تسجيل الدخول",
    "fa": "ورود",
  },
  "tabRegister": {
    "en": "Register",
    "ja": "新規登録",
    "ko": "회원가입",
    "zh-CN": "注册",
    "zh-TW": "註冊",
    "th": "สมัครสมาชิก",
    "vi": "Đăng ký",
    "ru": "Регистрация",
    "fr": "Inscription",
    "de": "Registrieren",
    "ar": "إنشاء حساب",
    "fa": "ثبت‌نام",
  },
  "magicLinkBanner": {
    "en": "Enter your email to receive a one-time sign-in code.",
    "ja": "メールアドレスを入力すると、ワンタイム認証コードをお送りします。",
    "ko": "이메일을 입력하면 일회용 로그인 코드를 보내드립니다.",
    "zh-CN": "输入邮箱即可收到一次性登录验证码。",
    "zh-TW": "輸入電子郵件即可收到一次性登入驗證碼。",
    "th": "กรอกอีเมลเพื่อรับรหัสเข้าสู่ระบบแบบใช้ครั้งเดียว",
    "vi": "Nhập email để nhận mã đăng nhập dùng một lần.",
    "ru": "Введите email, чтобы получить одноразовый код для входа.",
    "fr": "Saisissez votre e-mail pour recevoir un code de connexion à usage unique.",
    "de": "E-Mail eingeben, um einen Einmal-Anmeldecode zu erhalten.",
    "ar": "أدخل بريدك الإلكتروني لاستلام رمز دخول لمرة واحدة.",
    "fa": "ایمیل خود را وارد کنید تا کد ورود یک‌بارمصرف دریافت کنید.",
  },
  "forgotBanner": {
    "en": "Enter your email to receive a password reset link.",
    "ja": "メールアドレスを入力すると、パスワード再設定リンクをお送りします。",
    "ko": "이메일을 입력하면 비밀번호 재설정 링크를 보내드립니다.",
    "zh-CN": "输入邮箱即可收到密码重置链接。",
    "zh-TW": "輸入電子郵件即可收到密碼重設連結。",
    "th": "กรอกอีเมลเพื่อรับลิงก์รีเซ็ตรหัสผ่าน",
    "vi": "Nhập email để nhận liên kết đặt lại mật khẩu.",
    "ru": "Введите email, чтобы получить ссылку для сброса пароля.",
    "fr": "Saisissez votre e-mail pour recevoir un lien de réinitialisation du mot de passe.",
    "de": "E-Mail eingeben, um einen Link zum Zurücksetzen des Passworts zu erhalten.",
    "ar": "أدخل بريدك الإلكتروني لاستلام رابط إعادة تعيين كلمة المرور.",
    "fa": "ایمیل خود را وارد کنید تا لینک بازیابی رمز عبور دریافت کنید.",
  },
  "checkEmail": {
    "en": "Check your email!",
    "ja": "メールを確認してください！",
    "ko": "이메일을 확인하세요!",
    "zh-CN": "请查收邮件！",
    "zh-TW": "請查看電子郵件！",
    "th": "กรุณาตรวจสอบอีเมล!",
    "vi": "Kiểm tra email của bạn!",
    "ru": "Проверьте почту!",
    "fr": "Vérifiez votre e-mail !",
    "de": "Prüfen Sie Ihre E-Mail!",
    "ar": "تحقق من بريدك الإلكتروني!",
    "fa": "ایمیل خود را بررسی کنید!",
  },
  "magicSentDesc": {
    "en": "We sent a magic link to {email}. Click the link to sign in.",
    "ja": "{email} にマジックリンクを送信しました。リンクをクリックしてログインしてください。",
    "ko": "{email}로 매직 링크를 보냈습니다. 링크를 클릭하여 로그인하세요.",
    "zh-CN": "我们已向 {email} 发送了免密登录链接，点击链接即可登录。",
    "zh-TW": "我們已將免密碼登入連結寄至 {email}，點擊連結即可登入。",
    "th": "เราส่งลิงก์เข้าสู่ระบบไปยัง {email} แล้ว คลิกลิงก์เพื่อเข้าสู่ระบบ",
    "vi": "Chúng tôi đã gửi liên kết đăng nhập tới {email}. Nhấp vào liên kết để đăng nhập.",
    "ru": "Мы отправили ссылку для входа на {email}. Нажмите на ссылку, чтобы войти.",
    "fr": "Nous avons envoyé un lien de connexion à {email}. Cliquez sur le lien pour vous connecter.",
    "de": "Wir haben einen Anmeldelink an {email} gesendet. Klicken Sie auf den Link.",
    "ar": "أرسلنا رابط الدخول إلى {email}. اضغط على الرابط لتسجيل الدخول.",
    "fa": "لینک ورود به {email} ارسال شد. روی لینک کلیک کنید تا وارد شوید.",
  },
  "resetSentDesc": {
    "en": "If an account exists for {email}, we sent password reset instructions.",
    "ja": "{email} のアカウントが存在する場合、パスワード再設定手順を送信しました。",
    "ko": "{email} 계정이 존재하면 비밀번호 재설정 안내를 보냈습니다.",
    "zh-CN": "如果 {email} 存在对应账户，我们已发送密码重置说明。",
    "zh-TW": "如果 {email} 存在對應帳戶，我們已寄出密碼重設說明。",
    "th": "หากมีบัญชีสำหรับ {email} เราจะส่งคำแนะนำการรีเซ็ตรหัสผ่านให้",
    "vi": "Nếu có tài khoản cho {email}, chúng tôi đã gửi hướng dẫn đặt lại mật khẩu.",
    "ru": "Если аккаунт для {email} существует, мы отправили инструкции по сбросу пароля.",
    "fr": "Si un compte existe pour {email}, nous avons envoyé les instructions de réinitialisation.",
    "de": "Wenn ein Konto für {email} existiert, haben wir Anweisungen gesendet.",
    "ar": "إذا كان هناك حساب لـ {email}، فقد أرسلنا تعليمات إعادة تعيين كلمة المرور.",
    "fa": "اگر حسابی برای {email} وجود داشته باشد، دستورالعمل بازیابی رمز ارسال شده است.",
  },
  "errorTitle": {
    "en": "Error",
    "ja": "エラー",
    "ko": "오류",
    "zh-CN": "出错了",
    "zh-TW": "發生錯誤",
    "th": "เกิดข้อผิดพลาด",
    "vi": "Lỗi",
    "ru": "Ошибка",
    "fr": "Erreur",
    "de": "Fehler",
    "ar": "خطأ",
    "fa": "خطا",
  },
  "oauthUnavailable": {
    "en": "Social sign-in is currently being configured. Please use email + password below.",
    "ja": "ソーシャルログインは現在設定中です。しばらくはメールとパスワードをご利用ください。",
    "ko": "소셜 로그인이 설정 중입니다. 지금은 이메일과 비밀번호를 사용해 주세요.",
    "zh-CN": "社交账号登录正在配置中，请先使用邮箱和密码登录。",
    "zh-TW": "社群帳號登入設定中，請先使用電子郵件與密碼。",
    "th": "กำลังตั้งค่าการเข้าสู่ระบบด้วยโซเชียล กรุณาใช้อีเมลและรหัสผ่านก่อน",
    "vi": "Đăng nhập mạng xã hội đang được thiết lập. Vui lòng dùng email và mật khẩu.",
    "ru": "Вход через соцсети настраивается. Пока используйте email и пароль.",
    "fr": "La connexion sociale est en cours de configuration. Utilisez e-mail et mot de passe.",
    "de": "Soziale Anmeldung wird eingerichtet. Nutzen Sie E-Mail und Passwort.",
    "ar": "تسجيل الدخول عبر الشبكات الاجتماعية قيد الإعداد. استخدم البريد الإلكتروني وكلمة المرور.",
    "fa": "ورود با شبکه‌های اجتماعی در حال راه‌اندازی است. فعلاً از ایمیل و رمز عبور استفاده کنید.",
  },
  "displayNameLabel": {
    "en": "Display Name",
    "ja": "表示名",
    "ko": "표시 이름",
    "zh-CN": "昵称",
    "zh-TW": "暱稱",
    "th": "ชื่อที่แสดง",
    "vi": "Tên hiển thị",
    "ru": "Отображаемое имя",
    "fr": "Nom d'affichage",
    "de": "Anzeigename",
    "ar": "الاسم المعروض",
    "fa": "نام نمایشی",
  },
  "displayNamePlaceholder": {
    "en": "Your display name",
    "ja": "表示名を入力",
    "ko": "표시 이름 입력",
    "zh-CN": "请输入昵称",
    "zh-TW": "請輸入暱稱",
    "th": "กรอกชื่อที่แสดง",
    "vi": "Nhập tên hiển thị",
    "ru": "Введите имя",
    "fr": "Votre nom d'affichage",
    "de": "Ihr Anzeigename",
    "ar": "أدخل اسمك",
    "fa": "نام خود را وارد کنید",
  },
  "emailLabel": {
    "en": "Email",
    "ja": "メールアドレス",
    "ko": "이메일",
    "zh-CN": "邮箱",
    "zh-TW": "電子郵件",
    "th": "อีเมล",
    "vi": "Email",
    "ru": "Email",
    "fr": "E-mail",
    "de": "E-Mail",
    "ar": "البريد الإلكتروني",
    "fa": "ایمیل",
  },
  "emailPlaceholder": {
    "en": "you@example.com",
    "ja": "you@example.com",
    "ko": "you@example.com",
    "zh-CN": "you@example.com",
    "zh-TW": "you@example.com",
    "th": "you@example.com",
    "vi": "you@example.com",
    "ru": "you@example.com",
    "fr": "you@example.com",
    "de": "you@example.com",
    "ar": "you@example.com",
    "fa": "you@example.com",
  },
  "passwordLabel": {
    "en": "Password",
    "ja": "パスワード",
    "ko": "비밀번호",
    "zh-CN": "密码",
    "zh-TW": "密碼",
    "th": "รหัสผ่าน",
    "vi": "Mật khẩu",
    "ru": "Пароль",
    "fr": "Mot de passe",
    "de": "Passwort",
    "ar": "كلمة المرور",
    "fa": "رمز عبور",
  },
  "confirmEmailLabel": {
    "en": "Confirm Email",
    "ja": "メールアドレス確認",
    "ko": "이메일 확인",
    "zh-CN": "确认邮箱",
    "zh-TW": "確認電子郵件",
    "th": "ยืนยันอีเมล",
    "vi": "Xác nhận email",
    "ru": "Подтвердите email",
    "fr": "Confirmer l'e-mail",
    "de": "E-Mail bestätigen",
    "ar": "تأكيد البريد الإلكتروني",
    "fa": "تأیید ایمیل",
  },
  "passwordPlaceholder": {
    "en": "At least 6 characters",
    "ja": "6文字以上",
    "ko": "6자 이상",
    "zh-CN": "至少 6 个字符",
    "zh-TW": "至少 6 個字元",
    "th": "อย่างน้อย 6 ตัวอักษร",
    "vi": "Tối thiểu 6 ký tự",
    "ru": "Не менее 6 символов",
    "fr": "6 caractères minimum",
    "de": "Mindestens 6 Zeichen",
    "ar": "6 أحرف على الأقل",
    "fa": "حداقل ۶ کاراکتر",
  },
  "confirmEmailPlaceholder": {
    "en": "Confirm your email",
    "ja": "メールアドレスを再入力",
    "ko": "이메일 다시 입력",
    "zh-CN": "请再次输入邮箱",
    "zh-TW": "請再次輸入電子郵件",
    "th": "กรอกอีเมลอีกครั้ง",
    "vi": "Nhập lại email",
    "ru": "Введите email ещё раз",
    "fr": "Confirmez votre e-mail",
    "de": "E-Mail erneut eingeben",
    "ar": "أعد إدخال البريد الإلكتروني",
    "fa": "ایمیل را دوباره وارد کنید",
  },
  "processing": {
    "en": "Processing…",
    "ja": "処理中…",
    "ko": "처리 중…",
    "zh-CN": "处理中…",
    "zh-TW": "處理中…",
    "th": "กำลังประมวลผล…",
    "vi": "Đang xử lý…",
    "ru": "Обработка…",
    "fr": "Traitement…",
    "de": "Verarbeitung…",
    "ar": "جارٍ المعالجة…",
    "fa": "در حال پردازش…",
  },
  "submitSignIn": {
    "en": "Sign In",
    "ja": "ログイン",
    "ko": "로그인",
    "zh-CN": "登录",
    "zh-TW": "登入",
    "th": "เข้าสู่ระบบ",
    "vi": "Đăng nhập",
    "ru": "Войти",
    "fr": "Se connecter",
    "de": "Anmelden",
    "ar": "تسجيل الدخول",
    "fa": "ورود",
  },
  "submitRegister": {
    "en": "Create Account",
    "ja": "アカウント作成",
    "ko": "계정 만들기",
    "zh-CN": "创建账户",
    "zh-TW": "建立帳戶",
    "th": "สร้างบัญชี",
    "vi": "Tạo tài khoản",
    "ru": "Создать аккаунт",
    "fr": "Créer un compte",
    "de": "Konto erstellen",
    "ar": "إنشاء حساب",
    "fa": "ایجاد حساب",
  },
  "submitMagicLink": {
    "en": "Send Verification Code",
    "ja": "認証コードを送信",
    "ko": "인증 코드 보내기",
    "zh-CN": "发送验证码",
    "zh-TW": "寄送驗證碼",
    "th": "ส่งรหัสยืนยัน",
    "vi": "Gửi mã xác minh",
    "ru": "Отправить код подтверждения",
    "fr": "Envoyer le code de vérification",
    "de": "Verifizierungscode senden",
    "ar": "إرسال رمز التحقق",
    "fa": "ارسال کد تأیید",
  },
  "submitReset": {
    "en": "Send Reset Link",
    "ja": "再設定リンクを送信",
    "ko": "재설정 링크 보내기",
    "zh-CN": "发送重置链接",
    "zh-TW": "寄送重設連結",
    "th": "ส่งลิงก์รีเซ็ต",
    "vi": "Gửi liên kết đặt lại",
    "ru": "Отправить ссылку для сброса",
    "fr": "Envoyer le lien de réinitialisation",
    "de": "Reset-Link senden",
    "ar": "إرسال رابط إعادة التعيين",
    "fa": "ارسال لینک بازیابی",
  },
  "orContinueWith": {
    "en": "or continue with",
    "ja": "または次で続ける",
    "ko": "또는 계속하기",
    "zh-CN": "或使用以下方式继续",
    "zh-TW": "或使用以下方式繼續",
    "th": "หรือดำเนินการต่อด้วย",
    "vi": "hoặc tiếp tục với",
    "ru": "или продолжить через",
    "fr": "ou continuer avec",
    "de": "oder weiter mit",
    "ar": "أو المتابعة عبر",
    "fa": "یا ادامه با",
  },
  "demoActive": {
    "en": "Demo mode is active. Use demo credentials to explore.",
    "ja": "デモモードが有効です。デモ認証情報でお試しください。",
    "ko": "데모 모드가 활성화되었습니다. 데모 계정으로 둘러보세요.",
    "zh-CN": "当前为演示模式，可使用演示账号体验。",
    "zh-TW": "目前為示範模式，可使用示範帳號體驗。",
    "th": "โหมดสาธิตเปิดใช้งานอยู่ ใช้ข้อมูลสาธิตเพื่อสำรวจ",
    "vi": "Chế độ demo đang bật. Dùng thông tin demo để khám phá.",
    "ru": "Демо-режим активен. Используйте демо-данные для входа.",
    "fr": "Mode démo activé. Utilisez les identifiants de démo.",
    "de": "Demo-Modus aktiv. Nutzen Sie die Demo-Zugangsdaten.",
    "ar": "وضع التجربة مفعّل. استخدم بيانات التجربة للاستكشاف.",
    "fa": "حالت نمایشی فعال است. از اطلاعات نمایشی استفاده کنید.",
  },
  "tryDemo": {
    "en": "Try Demo Account",
    "ja": "デモアカウントで試す",
    "ko": "데모 계정 사용해보기",
    "zh-CN": "使用演示账号",
    "zh-TW": "使用示範帳號",
    "th": "ลองใช้บัญชีสาธิต",
    "vi": "Dùng tài khoản demo",
    "ru": "Попробовать демо-аккаунт",
    "fr": "Essayer le compte démo",
    "de": "Demo-Konto ausprobieren",
    "ar": "تجربة الحساب التجريبي",
    "fa": "استفاده از حساب نمایشی",
  },
  "noAccount": {
    "en": "No account?",
    "ja": "アカウントをお持ちでない方",
    "ko": "계정이 없으신가요?",
    "zh-CN": "还没有账户？",
    "zh-TW": "還沒有帳戶？",
    "th": "ยังไม่มีบัญชี?",
    "vi": "Chưa có tài khoản?",
    "ru": "Нет аккаунта?",
    "fr": "Pas de compte ?",
    "de": "Kein Konto?",
    "ar": "ليس لديك حساب؟",
    "fa": "حساب ندارید؟",
  },
  "signUp": {
    "en": "Sign up",
    "ja": "新規登録",
    "ko": "회원가입",
    "zh-CN": "立即注册",
    "zh-TW": "立即註冊",
    "th": "สมัครสมาชิก",
    "vi": "Đăng ký",
    "ru": "Зарегистрироваться",
    "fr": "S'inscrire",
    "de": "Registrieren",
    "ar": "سجّل الآن",
    "fa": "ثبت‌نام",
  },
  "magicLink": {
    "en": "Email code",
    "ja": "メール認証コード",
    "ko": "이메일 인증 코드",
    "zh-CN": "邮箱验证码",
    "zh-TW": "信箱驗證碼",
    "th": "รหัสทางอีเมล",
    "vi": "Mã email",
    "ru": "Код по email",
    "fr": "Code e-mail",
    "de": "E-Mail-Code",
    "ar": "رمز البريد الإلكتروني",
    "fa": "کد ایمیل",
  },
  "forgotPassword": {
    "en": "Forgot password",
    "ja": "パスワードをお忘れの方",
    "ko": "비밀번호 찾기",
    "zh-CN": "忘记密码",
    "zh-TW": "忘記密碼",
    "th": "ลืมรหัสผ่าน",
    "vi": "Quên mật khẩu",
    "ru": "Забыли пароль",
    "fr": "Mot de passe oublié",
    "de": "Passwort vergessen",
    "ar": "نسيت كلمة المرور",
    "fa": "فراموشی رمز عبور",
  },
  "haveAccount": {
    "en": "Have an account?",
    "ja": "アカウントをお持ちの方",
    "ko": "계정이 있으신가요?",
    "zh-CN": "已有账户？",
    "zh-TW": "已有帳戶？",
    "th": "มีบัญชีแล้ว?",
    "vi": "Đã có tài khoản?",
    "ru": "Есть аккаунт?",
    "fr": "Déjà un compte ?",
    "de": "Schon ein Konto?",
    "ar": "لديك حساب؟",
    "fa": "حساب دارید؟",
  },
  "signIn": {
    "en": "Sign in",
    "ja": "ログイン",
    "ko": "로그인",
    "zh-CN": "去登录",
    "zh-TW": "前往登入",
    "th": "เข้าสู่ระบบ",
    "vi": "Đăng nhập",
    "ru": "Войти",
    "fr": "Se connecter",
    "de": "Anmelden",
    "ar": "تسجيل الدخول",
    "fa": "ورود",
  },
  "backToSignIn": {
    "en": "Back to sign in",
    "ja": "ログインに戻る",
    "ko": "로그인으로 돌아가기",
    "zh-CN": "返回登录",
    "zh-TW": "返回登入",
    "th": "กลับไปเข้าสู่ระบบ",
    "vi": "Quay lại đăng nhập",
    "ru": "Вернуться ко входу",
    "fr": "Retour à la connexion",
    "de": "Zurück zur Anmeldung",
    "ar": "العودة إلى تسجيل الدخول",
    "fa": "بازگشت به ورود",
  },
  "agreeTerms": {
    "en": "By continuing, you agree to our {terms} and {privacy}.",
    "ja": "続行すると、{terms} と {privacy} に同意したことになります。",
    "ko": "계속하면 {terms} 및 {privacy}에 동의하는 것입니다.",
    "zh-CN": "继续即表示您同意我们的{terms}和{privacy}。",
    "zh-TW": "繼續即表示您同意我們的{terms}與{privacy}。",
    "th": "การดำเนินการต่อถือว่าคุณยอมรับ{terms}และ{privacy}ของเรา",
    "vi": "Tiếp tục nghĩa là bạn đồng ý với {terms} và {privacy} của chúng tôi.",
    "ru": "Продолжая, вы соглашаетесь с {terms} и {privacy}.",
    "fr": "En continuant, vous acceptez nos {terms} et notre {privacy}.",
    "de": "Mit der Fortsetzung stimmen Sie unseren {terms} und {privacy} zu.",
    "ar": "بالمتابعة أنت توافق على {terms} و{privacy}.",
    "fa": "با ادامه دادن، {terms} و {privacy} ما را می‌پذیرید.",
  },
  "terms": {
    "en": "Terms of Service",
    "ja": "利用規約",
    "ko": "이용약관",
    "zh-CN": "服务条款",
    "zh-TW": "服務條款",
    "th": "ข้อกำหนดการใช้งาน",
    "vi": "Điều khoản dịch vụ",
    "ru": "Условиями использования",
    "fr": "Conditions d'utilisation",
    "de": "Nutzungsbedingungen",
    "ar": "شروط الخدمة",
    "fa": "شرایط استفاده",
  },
  "privacy": {
    "en": "Privacy Policy",
    "ja": "プライバシーポリシー",
    "ko": "개인정보처리방침",
    "zh-CN": "隐私政策",
    "zh-TW": "隱私權政策",
    "th": "นโยบายความเป็นส่วนตัว",
    "vi": "Chính sách bảo mật",
    "ru": "Политикой конфиденциальности",
    "fr": "Politique de confidentialité",
    "de": "Datenschutzrichtlinie",
    "ar": "سياسة الخصوصية",
    "fa": "سیاست حفظ حریم خصوصی",
  },
  "redirecting": {
    "en": "Redirecting…",
    "ja": "リダイレクト中…",
    "ko": "이동 중…",
    "zh-CN": "正在跳转…",
    "zh-TW": "正在跳轉…",
    "th": "กำลังเปลี่ยนหน้า…",
    "vi": "Đang chuyển hướng…",
    "ru": "Перенаправление…",
    "fr": "Redirection…",
    "de": "Weiterleitung…",
    "ar": "جارٍ التحويل…",
    "fa": "در حال انتقال…",
  },
  "providerSetup": {
    "en": "{provider} sign-in is being set up. Please use email + password for now.",
    "ja": "{provider} のログインは現在設定中です。しばらくはメールとパスワードをご利用ください。",
    "ko": "{provider} 로그인이 설정 중입니다. 지금은 이메일과 비밀번호를 사용해 주세요.",
    "zh-CN": "{provider} 登录正在配置中，请先使用邮箱和密码登录。",
    "zh-TW": "{provider} 登入設定中，請先使用電子郵件與密碼。",
    "th": "การเข้าสู่ระบบด้วย {provider} กำลังตั้งค่า กรุณาใช้อีเมลและรหัสผ่านก่อน",
    "vi": "Đăng nhập {provider} đang được thiết lập. Vui lòng dùng email và mật khẩu.",
    "ru": "Вход через {provider} настраивается. Пока используйте email и пароль.",
    "fr": "La connexion {provider} est en cours de configuration. Utilisez e-mail et mot de passe.",
    "de": "{provider}-Anmeldung wird eingerichtet. Nutzen Sie E-Mail und Passwort.",
    "ar": "تسجيل الدخول عبر {provider} قيد الإعداد. استخدم البريد الإلكتروني وكلمة المرور.",
    "fa": "ورود با {provider} در حال راه‌اندازی است. فعلاً از ایمیل و رمز عبور استفاده کنید.",
  },
  "oauthFailed": {
    "en": "OAuth sign-in failed. Please try email + password.",
    "ja": "ソーシャルログインに失敗しました。メールとパスワードをお試しください。",
    "ko": "소셜 로그인에 실패했습니다. 이메일과 비밀번호를 시도해 주세요.",
    "zh-CN": "社交登录失败，请尝试邮箱和密码。",
    "zh-TW": "社群登入失敗，請嘗試電子郵件與密碼。",
    "th": "การเข้าสู่ระบบด้วยโซเชียลล้มเหลว กรุณาลองอีเมลและรหัสผ่าน",
    "vi": "Đăng nhập mạng xã hội thất bại. Vui lòng thử email và mật khẩu.",
    "ru": "Вход через соцсети не удался. Попробуйте email и пароль.",
    "fr": "Échec de la connexion sociale. Essayez e-mail et mot de passe.",
    "de": "Soziale Anmeldung fehlgeschlagen. Versuchen Sie E-Mail und Passwort.",
    "ar": "فشل تسجيل الدخول عبر الشبكات الاجتماعية. جرّب البريد الإلكتروني وكلمة المرور.",
    "fa": "ورود با شبکه‌های اجتماعی ناموفق بود. ایمیل و رمز عبور را امتحان کنید.",
  },
  "resetTitle": {
    "en": "Set a new password",
    "ja": "新しいパスワードを設定",
    "ko": "새 비밀번호 설정",
    "zh-CN": "设置新密码",
    "zh-TW": "設定新密碼",
    "th": "ตั้งรหัสผ่านใหม่",
    "vi": "Đặt mật khẩu mới",
    "ru": "Задайте новый пароль",
    "fr": "Définir un nouveau mot de passe",
    "de": "Neues Passwort festlegen",
    "ar": "تعيين كلمة مرور جديدة",
    "fa": "تنظیم رمز عبور جدید",
  },
  "newPasswordLabel": {
    "en": "New Password",
    "ja": "新しいパスワード",
    "ko": "새 비밀번호",
    "zh-CN": "新密码",
    "zh-TW": "新密碼",
    "th": "รหัสผ่านใหม่",
    "vi": "Mật khẩu mới",
    "ru": "Новый пароль",
    "fr": "Nouveau mot de passe",
    "de": "Neues Passwort",
    "ar": "كلمة المرور الجديدة",
    "fa": "رمز عبور جدید",
  },
  "newPasswordPlaceholder": {
    "en": "At least 8 characters",
    "ja": "8文字以上",
    "ko": "8자 이상",
    "zh-CN": "至少 8 个字符",
    "zh-TW": "至少 8 個字元",
    "th": "อย่างน้อย 8 ตัวอักษร",
    "vi": "Tối thiểu 8 ký tự",
    "ru": "Не менее 8 символов",
    "fr": "8 caractères minimum",
    "de": "Mindestens 8 Zeichen",
    "ar": "8 أحرف على الأقل",
    "fa": "حداقل ۸ کاراکتر",
  },
  "confirmPasswordLabel": {
    "en": "Confirm Password",
    "ja": "パスワード（確認）",
    "ko": "비밀번호 확인",
    "zh-CN": "确认新密码",
    "zh-TW": "確認新密碼",
    "th": "ยืนยันรหัสผ่าน",
    "vi": "Xác nhận mật khẩu",
    "ru": "Подтвердите пароль",
    "fr": "Confirmer le mot de passe",
    "de": "Passwort bestätigen",
    "ar": "تأكيد كلمة المرور",
    "fa": "تأیید رمز عبور",
  },
  "resetSubmit": {
    "en": "Update Password",
    "ja": "パスワードを更新",
    "ko": "비밀번호 업데이트",
    "zh-CN": "更新密码",
    "zh-TW": "更新密碼",
    "th": "อัปเดตรหัสผ่าน",
    "vi": "Cập nhật mật khẩu",
    "ru": "Обновить пароль",
    "fr": "Mettre à jour",
    "de": "Passwort aktualisieren",
    "ar": "تحديث كلمة المرور",
    "fa": "به‌روزرسانی رمز عبور",
  },
  "resetDone": {
    "en": "Password updated! Redirecting…",
    "ja": "パスワードを更新しました！リダイレクト中…",
    "ko": "비밀번호가 업데이트되었습니다! 이동 중…",
    "zh-CN": "密码已更新！正在跳转…",
    "zh-TW": "密碼已更新！正在跳轉…",
    "th": "อัปเดตรหัสผ่านแล้ว! กำลังเปลี่ยนหน้า…",
    "vi": "Đã cập nhật mật khẩu! Đang chuyển hướng…",
    "ru": "Пароль обновлён! Перенаправление…",
    "fr": "Mot de passe mis à jour ! Redirection…",
    "de": "Passwort aktualisiert! Weiterleitung…",
    "ar": "تم تحديث كلمة المرور! جارٍ التحويل…",
    "fa": "رمز عبور به‌روزرسانی شد! در حال انتقال…",
  },
  "resetInvalid": {
    "en": "This reset link is invalid or has expired. Please request a new one.",
    "ja": "この再設定リンクは無効または期限切れです。新しいリンクをリクエストしてください。",
    "ko": "이 재설정 링크는 유효하지 않거나 만료되었습니다. 새 링크를 요청하세요.",
    "zh-CN": "该重置链接无效或已过期，请重新申请。",
    "zh-TW": "此重設連結無效或已過期，請重新申請。",
    "th": "ลิงก์รีเซ็ตนี้ไม่ถูกต้องหรือหมดอายุแล้ว กรุณาขอลิงก์ใหม่",
    "vi": "Liên kết đặt lại này không hợp lệ hoặc đã hết hạn. Vui lòng yêu cầu liên kết mới.",
    "ru": "Эта ссылка недействительна или истекла. Запросите новую ссылку.",
    "fr": "Ce lien est invalide ou expiré. Demandez-en un nouveau.",
    "de": "Dieser Link ist ungültig oder abgelaufen. Fordern Sie einen neuen an.",
    "ar": "رابط إعادة التعيين غير صالح أو منتهي. اطلب رابطًا جديدًا.",
    "fa": "این لینک بازیابی نامعتبر یا منقضی است. لینک جدیدی درخواست کنید.",
  },
  "resetLinkToLogin": {
    "en": "Back to sign in",
    "ja": "ログインに戻る",
    "ko": "로그인으로 돌아가기",
    "zh-CN": "返回登录",
    "zh-TW": "返回登入",
    "th": "กลับไปเข้าสู่ระบบ",
    "vi": "Quay lại đăng nhập",
    "ru": "Вернуться ко входу",
    "fr": "Retour à la connexion",
    "de": "Zurück zur Anmeldung",
    "ar": "العودة إلى تسجيل الدخول",
    "fa": "بازگشت به ورود",
  },
  "updateFailed": {
    "en": "Password update failed. Please try again.",
    "ja": "パスワードの更新に失敗しました。もう一度お試しください。",
    "ko": "비밀번호 업데이트에 실패했습니다. 다시 시도해 주세요.",
    "zh-CN": "密码更新失败，请重试。",
    "zh-TW": "密碼更新失敗，請重試。",
    "th": "อัปเดตรหัสผ่านล้มเหลว กรุณาลองอีกครั้ง",
    "vi": "Cập nhật mật khẩu thất bại. Vui lòng thử lại.",
    "ru": "Не удалось обновить пароль. Попробуйте ещё раз.",
    "fr": "Échec de la mise à jour. Réessayez.",
    "de": "Aktualisierung fehlgeschlagen. Versuchen Sie es erneut.",
    "ar": "فشل تحديث كلمة المرور. حاول مرة أخرى.",
    "fa": "به‌روزرسانی رمز عبور ناموفق بود. دوباره تلاش کنید.",
  },
  "resetPageTitle": {
    "en": "Reset Password - ChinaConnect",
    "ja": "パスワード再設定 - ChinaConnect",
    "ko": "비밀번호 재설정 - ChinaConnect",
    "zh-CN": "重置密码 - ChinaConnect",
    "zh-TW": "重設密碼 - ChinaConnect",
    "th": "รีเซ็ตรหัสผ่าน - ChinaConnect",
    "vi": "Đặt lại mật khẩu - ChinaConnect",
    "ru": "Сброс пароля - ChinaConnect",
    "fr": "Réinitialiser le mot de passe - ChinaConnect",
    "de": "Passwort zurücksetzen - ChinaConnect",
    "ar": "إعادة تعيين كلمة المرور - ChinaConnect",
    "fa": "بازیابی رمز عبور - ChinaConnect",
  },


  "profileUserNotFound": {
    "en": "User not found",
    "ja": "ユーザーが見つかりません",
    "ko": "사용자를 찾을 수 없습니다",
    "zh-CN": "用户未找到",
    "zh-TW": "找不到用戶",
    "th": "ไม่พบผู้ใช้",
    "vi": "Không tìm thấy người dùng",
    "ru": "Пользователь не найден",
    "fr": "Utilisateur introuvable",
    "de": "Benutzer nicht gefunden",
    "ar": "المستخدم غير موجود",
    "fa": "کاربر یافت نشد"
  },
  "profileNotFoundDesc": {
    "en": "This user doesn't exist or has been removed.",
    "ja": "このユーザーは存在しないか、削除されています。",
    "ko": "이 사용자는 존재하지 않거나 삭제되었습니다.",
    "zh-CN": "该用户不存在或已被移除。",
    "zh-TW": "該用戶不存在或已被移除。",
    "th": "ผู้ใช้นี้ไม่มีอยู่หรือถูกลบแล้ว",
    "vi": "Người dùng này không tồn tại hoặc đã bị xóa.",
    "ru": "Этот пользователь не существует или был удалён.",
    "fr": "Cet utilisateur n'existe pas ou a été supprimé.",
    "de": "Dieser Benutzer existiert nicht oder wurde entfernt.",
    "ar": "هذا المستخدم غير موجود أو تمت إزالته.",
    "fa": "این کاربر وجود ندارد یا حذف شده است."
  },
  "profileEdit": {
    "en": "Edit Profile",
    "ja": "プロフィール編集",
    "ko": "프로필 편집",
    "zh-CN": "编辑资料",
    "zh-TW": "編輯資料",
    "th": "แก้ไขโปรไฟล์",
    "vi": "Chỉnh sửa hồ sơ",
    "ru": "Редактировать профиль",
    "fr": "Modifier le profil",
    "de": "Profil bearbeiten",
    "ar": "تعديل الملف الشخصي",
    "fa": "ویرایش پروفایل"
  },
  "profileDisplayName": {
    "en": "Display Name",
    "ja": "表示名",
    "ko": "표시 이름",
    "zh-CN": "显示名称",
    "zh-TW": "顯示名稱",
    "th": "ชื่อที่แสดง",
    "vi": "Tên hiển thị",
    "ru": "Отображаемое имя",
    "fr": "Nom affiché",
    "de": "Anzeigename",
    "ar": "الاسم المعروض",
    "fa": "نام نمایشی"
  },
  "profileBio": {
    "en": "Bio",
    "ja": "自己紹介",
    "ko": "소개",
    "zh-CN": "个人简介",
    "zh-TW": "個人簡介",
    "th": "ประวัติย่อ",
    "vi": "Giới thiệu",
    "ru": "О себе",
    "fr": "Bio",
    "de": "Bio",
    "ar": "نبذة",
    "fa": "درباره من"
  },
  "profileNationality": {
    "en": "Nationality",
    "ja": "国籍",
    "ko": "국적",
    "zh-CN": "国籍",
    "zh-TW": "國籍",
    "th": "สัญชาติ",
    "vi": "Quốc tịch",
    "ru": "Гражданство",
    "fr": "Nationalité",
    "de": "Staatsangehörigkeit",
    "ar": "الجنسية",
    "fa": "ملیت"
  },
  "profileNationalityPlaceholder": {
    "en": "e.g., United States",
    "ja": "例：日本",
    "ko": "예: 대한민국",
    "zh-CN": "例如：中国",
    "zh-TW": "例如：台灣",
    "th": "เช่น ประเทศไทย",
    "vi": "Ví dụ: Việt Nam",
    "ru": "например, Россия",
    "fr": "ex. France",
    "de": "z. B. Deutschland",
    "ar": "مثال: السعودية",
    "fa": "مثلاً ایران"
  },
  "profileCancel": {
    "en": "Cancel",
    "ja": "キャンセル",
    "ko": "취소",
    "zh-CN": "取消",
    "zh-TW": "取消",
    "th": "ยกเลิก",
    "vi": "Hủy",
    "ru": "Отмена",
    "fr": "Annuler",
    "de": "Abbrechen",
    "ar": "إلغاء",
    "fa": "لغو"
  },
  "profileSave": {
    "en": "Save Changes",
    "ja": "変更を保存",
    "ko": "변경사항 저장",
    "zh-CN": "保存更改",
    "zh-TW": "儲存變更",
    "th": "บันทึกการเปลี่ยนแปลง",
    "vi": "Lưu thay đổi",
    "ru": "Сохранить",
    "fr": "Enregistrer",
    "de": "Änderungen speichern",
    "ar": "حفظ التغييرات",
    "fa": "ذخیره تغییرات"
  },
  "profilePosts": {
    "en": "Posts",
    "ja": "投稿",
    "ko": "게시물",
    "zh-CN": "帖子",
    "zh-TW": "貼文",
    "th": "โพสต์",
    "vi": "Bài đăng",
    "ru": "Посты",
    "fr": "Publications",
    "de": "Beiträge",
    "ar": "المنشورات",
    "fa": "نوشته‌ها"
  },
  "profileCheckins": {
    "en": "Check-ins",
    "ja": "チェックイン",
    "ko": "체크인",
    "zh-CN": "签到",
    "zh-TW": "打卡",
    "th": "เช็คอิน",
    "vi": "Điểm danh",
    "ru": "Отметки",
    "fr": "Check-ins",
    "de": "Check-ins",
    "ar": "تسجيلات الوصول",
    "fa": "چک‌این‌ها"
  },
  "profileLikesReceived": {
    "en": "Likes Received",
    "ja": "受け取ったいいね",
    "ko": "받은 좋아요",
    "zh-CN": "收到的赞",
    "zh-TW": "收到的讚",
    "th": "ไลก์ที่ได้รับ",
    "vi": "Lượt thích nhận được",
    "ru": "Полученные лайки",
    "fr": "J'aime reçus",
    "de": "Erhaltene Likes",
    "ar": "الإعجابات المستلمة",
    "fa": "لایک‌های دریافتی"
  },
  "profileBestAnswers": {
    "en": "Best Answers",
    "ja": "ベストアンサー",
    "ko": "베스트 답변",
    "zh-CN": "最佳回答",
    "zh-TW": "最佳回答",
    "th": "คำตอบยอดเยี่ยม",
    "vi": "Câu trả lời hay nhất",
    "ru": "Лучшие ответы",
    "fr": "Meilleures réponses",
    "de": "Beste Antworten",
    "ar": "أفضل الإجابات",
    "fa": "بهترین پاسخ‌ها"
  },
  "profileMemberSince": {
    "en": "Member since",
    "ja": "登録日",
    "ko": "가입일",
    "zh-CN": "加入时间",
    "zh-TW": "加入時間",
    "th": "สมาชิกตั้งแต่",
    "vi": "Thành viên từ",
    "ru": "Участник с",
    "fr": "Membre depuis",
    "de": "Mitglied seit",
    "ar": "عضو منذ",
    "fa": "عضو از"
  },
  "profileAnonymous": {
    "en": "Anonymous",
    "ja": "匿名ユーザー",
    "ko": "익명",
    "zh-CN": "匿名用户",
    "zh-TW": "匿名用戶",
    "th": "ไม่ระบุชื่อ",
    "vi": "Ẩn danh",
    "ru": "Аноним",
    "fr": "Anonyme",
    "de": "Anonym",
    "ar": "مجهول",
    "fa": "ناشناس"
  },
  "profileSignInRequired": {
    "en": "Sign in required",
    "ja": "ログインが必要です",
    "ko": "로그인이 필요합니다",
    "zh-CN": "需要登录",
    "zh-TW": "需要登入",
    "th": "ต้องเข้าสู่ระบบ",
    "vi": "Yêu cầu đăng nhập",
    "ru": "Требуется вход",
    "fr": "Connexion requise",
    "de": "Anmeldung erforderlich",
    "ar": "تسجيل الدخول مطلوب",
    "fa": "ورود الزامی است"
  },
  "profileSignInRequiredDesc": {
    "en": "Please sign in to view and edit your profile.",
    "ja": "プロフィールの表示・編集にはログインしてください。",
    "ko": "프로필을 보고 편집하려면 로그인하세요.",
    "zh-CN": "请登录后查看和编辑您的个人资料。",
    "zh-TW": "請登入後查看和編輯您的個人資料。",
    "th": "กรุณาเข้าสู่ระบบเพื่อดูและแก้ไขโปรไฟล์ของคุณ",
    "vi": "Vui lòng đăng nhập để xem và chỉnh sửa hồ sơ của bạn.",
    "ru": "Пожалуйста, войдите, чтобы просмотреть и редактировать профиль.",
    "fr": "Veuillez vous connecter pour voir et modifier votre profil.",
    "de": "Bitte melden Sie sich an, um Ihr Profil anzusehen und zu bearbeiten.",
    "ar": "يرجى تسجيل الدخول لعرض وتعديل ملفك الشخصي.",
    "fa": "لطفاً برای مشاهده و ویرایش پروفایل خود وارد شوید."
  },
  "profileUpdateSuccess": {
    "en": "Profile updated successfully.",
    "ja": "プロフィールを更新しました。",
    "ko": "프로필이 업데이트되었습니다.",
    "zh-CN": "个人资料更新成功。",
    "zh-TW": "個人資料更新成功。",
    "th": "อัปเดตโปรไฟล์สำเร็จ",
    "vi": "Đã cập nhật hồ sơ thành công.",
    "ru": "Профиль успешно обновлён.",
    "fr": "Profil mis à jour avec succès.",
    "de": "Profil erfolgreich aktualisiert.",
    "ar": "تم تحديث الملف الشخصي بنجاح.",
    "fa": "پروفایل با موفقیت به‌روزرسانی شد."
  },
  "profileUpdateError": {
    "en": "Failed to update profile. Please try again.",
    "ja": "プロフィールの更新に失敗しました。もう一度お試しください。",
    "ko": "프로필 업데이트에 실패했습니다. 다시 시도해 주세요.",
    "zh-CN": "个人资料更新失败，请重试。",
    "zh-TW": "個人資料更新失敗，請重試。",
    "th": "อัปเดตโปรไฟล์ไม่สำเร็จ โปรดลองอีกครั้ง",
    "vi": "Không thể cập nhật hồ sơ. Vui lòng thử lại.",
    "ru": "Не удалось обновить профиль. Попробуйте ещё раз.",
    "fr": "Échec de la mise à jour du profil. Veuillez réessayer.",
    "de": "Profil konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.",
    "ar": "تعذر تحديث الملف الشخصي. حاول مرة أخرى.",
    "fa": "به‌روزرسانی پروفایل ناموفق بود. دوباره تلاش کنید."
  },
  "callbackSigningYouIn": {
    "en": "Signing you in...",
    "ja": "サインイン中…",
    "ko": "로그인 중...",
    "zh-CN": "正在登录…",
    "zh-TW": "正在登入…",
    "th": "กำลังเข้าสู่ระบบ...",
    "vi": "Đang đăng nhập...",
    "ru": "Выполняется вход...",
    "fr": "Connexion en cours...",
    "de": "Anmeldung läuft...",
    "ar": "جارٍ تسجيل الدخول...",
    "fa": "در حال ورود..."
  },
  "callbackErrorTitle": {
    "en": "Verification failed",
    "ja": "認証に失敗しました",
    "ko": "인증에 실패했습니다",
    "zh-CN": "验证失败",
    "zh-TW": "驗證失敗",
    "th": "การยืนยันล้มเหลว",
    "vi": "Xác minh thất bại",
    "ru": "Не удалось подтвердить",
    "fr": "Échec de la vérification",
    "de": "Überprüfung fehlgeschlagen",
    "ar": "فشل التحقق",
    "fa": "تأیید ناموفق بود"
  },
  "callbackErrorDesc": {
    "en": "The confirmation link is invalid or has expired. Please try registering again.",
    "ja": "確認リンクが無効または期限切れです。もう一度ご登録ください。",
    "ko": "확인 링크가 유효하지 않거나 만료되었습니다. 다시 가입해 주세요.",
    "zh-CN": "确认链接无效或已过期，请重新注册。",
    "zh-TW": "確認連結無效或已過期，請重新註冊。",
    "th": "ลิงก์ยืนยันไม่ถูกต้องหรือหมดอายุ กรุณาลงทะเบียนอีกครั้ง",
    "vi": "Liên kết xác nhận không hợp lệ hoặc đã hết hạn. Vui lòng đăng ký lại.",
    "ru": "Ссылка подтверждения недействительна или истекла. Попробуйте зарегистрироваться снова.",
    "fr": "Le lien de confirmation est invalide ou a expiré. Veuillez réessayer de vous inscrire.",
    "de": "Der Bestätigungslink ist ungültig oder abgelaufen. Bitte registrieren Sie sich erneut.",
    "ar": "رابط التأكيد غير صالح أو منتهي الصلاحية. يرجى إعادة التسجيل.",
    "fa": "لینک تأیید نامعتبر یا منقضی است. لطفاً دوباره ثبت‌نام کنید."
  },
  "callbackUnexpected": {
    "en": "Something went wrong while completing sign-in. Please try again.",
    "ja": "サインインの完了中にエラーが発生しました。もう一度お試しください。",
    "ko": "로그인을 완료하는 중 문제가 발생했습니다. 다시 시도해 주세요.",
    "zh-CN": "完成登录时出现问题，请重试。",
    "zh-TW": "完成登入時發生問題，請重試。",
    "th": "เกิดข้อผิดพลาดขณะเข้าสู่ระบบ กรุณาลองอีกครั้ง",
    "vi": "Đã xảy ra lỗi khi hoàn tất đăng nhập. Vui lòng thử lại.",
    "ru": "Произошла ошибка при завершении входа. Попробуйте ещё раз.",
    "fr": "Une erreur est survenue lors de la connexion. Veuillez réessayer.",
    "de": "Beim Abschluss der Anmeldung ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    "ar": "حدث خطأ أثناء إكمال تسجيل الدخول. يرجى المحاولة مرة أخرى.",
    "fa": "هنگام تکمیل ورود خطایی رخ داد. دوباره تلاش کنید."
  },
  "callbackBackToSignIn": {
    "en": "Back to sign in",
    "ja": "ログインに戻る",
    "ko": "로그인으로 돌아가기",
    "zh-CN": "返回登录",
    "zh-TW": "返回登入",
    "th": "กลับไปเข้าสู่ระบบ",
    "vi": "Quay lại đăng nhập",
    "ru": "Вернуться ко входу",
    "fr": "Retour à la connexion",
    "de": "Zurück zur Anmeldung",
    "ar": "العودة إلى تسجيل الدخول",
    "fa": "بازگشت به ورود"
  },
  "otpSentDesc": {
    "en": "We sent a 6-digit code to {email}. Enter it below to sign in.",
    "ja": "{email} に6桁の認証コードを送信しました。下に入力してログインしてください。",
    "ko": "{email}로 6자리 인증 코드를 보냈습니다. 아래에 입력하여 로그인하세요.",
    "zh-CN": "我们已向 {email} 发送 6 位验证码，请输入验证码登录。",
    "zh-TW": "我們已將 6 位驗證碼寄至 {email}，請輸入驗證碼登入。",
    "th": "เราส่งรหัสยืนยัน 6 หลักไปยัง {email} แล้ว กรุณากรอกด้านล่างเพื่อเข้าสู่ระบบ",
    "vi": "Chúng tôi đã gửi mã xác minh 6 chữ số tới {email}. Nhập mã bên dưới để đăng nhập.",
    "ru": "Мы отправили 6-значный код на {email}. Введите его ниже, чтобы войти.",
    "fr": "Nous avons envoyé un code à 6 chiffres à {email}. Saisissez-le ci-dessous pour vous connecter.",
    "de": "Wir haben einen 6-stelligen Code an {email} gesendet. Geben Sie ihn unten ein, um sich anzumelden.",
    "ar": "أرسلنا رمزًا من 6 أرقام إلى {email}. أدخله أدناه لتسجيل الدخول.",
    "fa": "یک کد ۶ رقمی به {email} ارسال شد. برای ورود آن را در زیر وارد کنید."
  },
  "otpCodeLabel": {
    "en": "Verification code",
    "ja": "認証コード",
    "ko": "인증 코드",
    "zh-CN": "验证码",
    "zh-TW": "驗證碼",
    "th": "รหัสยืนยัน",
    "vi": "Mã xác minh",
    "ru": "Код подтверждения",
    "fr": "Code de vérification",
    "de": "Bestätigungscode",
    "ar": "رمز التحقق",
    "fa": "کد تأیید"
  },
  "otpCodePlaceholder": {
    "en": "6-digit code",
    "ja": "6桁のコード",
    "ko": "6자리 코드",
    "zh-CN": "6 位验证码",
    "zh-TW": "6 位驗證碼",
    "th": "รหัส 6 หลัก",
    "vi": "Mã 6 chữ số",
    "ru": "6-значный код",
    "fr": "Code à 6 chiffres",
    "de": "6-stelliger Code",
    "ar": "رمز من 6 أرقام",
    "fa": "کد ۶ رقمی"
  },
  "verifyCode": {
    "en": "Verify & Sign In",
    "ja": "認証してログイン",
    "ko": "인증 후 로그인",
    "zh-CN": "验证并登录",
    "zh-TW": "驗證並登入",
    "th": "ยืนยันและเข้าสู่ระบบ",
    "vi": "Xác minh và đăng nhập",
    "ru": "Подтвердить и войти",
    "fr": "Vérifier et se connecter",
    "de": "Verifizieren und anmelden",
    "ar": "تحقق وسجّل الدخول",
    "fa": "تأیید و ورود"
  },
  "resendCode": {
    "en": "Resend code",
    "ja": "コードを再送信",
    "ko": "코드 재전송",
    "zh-CN": "重新发送验证码",
    "zh-TW": "重新寄送驗證碼",
    "th": "ส่งรหัสอีกครั้ง",
    "vi": "Gửi lại mã",
    "ru": "Отправить код повторно",
    "fr": "Renvoyer le code",
    "de": "Code erneut senden",
    "ar": "إعادة إرسال الرمز",
    "fa": "ارسال مجدد کد"
  },
  "invalidCode": {
    "en": "Invalid or expired code. Please request a new one.",
    "ja": "コードが無効または期限切れです。新しいコードをリクエストしてください。",
    "ko": "코드가 잘못되었거나 만료되었습니다. 새 코드를 요청하세요.",
    "zh-CN": "验证码无效或已过期，请重新获取。",
    "zh-TW": "驗證碼無效或已過期，請重新取得。",
    "th": "รหัสไม่ถูกต้องหรือหมดอายุ กรุณาขอใหม่",
    "vi": "Mã không hợp lệ hoặc đã hết hạn. Vui lòng yêu cầu mã mới.",
    "ru": "Неверный или истёкший код. Запросите новый.",
    "fr": "Code invalide ou expiré. Veuillez en demander un nouveau.",
    "de": "Ungültiger oder abgelaufener Code. Bitte fordern Sie einen neuen an.",
    "ar": "الرمز غير صالح أو منتهي الصلاحية. يرجى طلب رمز جديد.",
    "fa": "کد نامعتبر یا منقضی شده است. لطفاً کد جدیدی درخواست کنید."
  },
};

/** Resolve the current UI language on the client (server-rendered lang first). */
export function detectAuthLang(): string {
  if (typeof window === "undefined") return "en";
  const w = window as unknown as { __I18N__?: { serverLang?: string } };
  const serverLang = w.__I18N__?.serverLang || "";
  // URL-prefixed pages are authoritative (e.g. /ja/auth/login).
  if (serverLang && serverLang !== "en") return serverLang;
  // Root (unprefixed) pages: prefer the user's explicit choice, then the
  // region cookie the worker set on first visit, so users are never stuck
  // on the English auth flow after being redirected to their language.
  try {
    const stored = localStorage.getItem("chinaconnect_language");
    if (stored) return stored;
  } catch {
    /* ignore */
  }
  try {
    const m = document.cookie.match(/(?:^|; )chinaconnect_language=([^;]+)/);
    if (m && m[1]) return m[1];
  } catch {
    /* ignore */
  }
  return serverLang || "en";
}

/** Translate an auth UI key into the given language (falls back to en). */
export function authT(lang: string, key: AuthKey, vars?: Record<string, string | number>): string {
  const l = (AUTH_LANGS as string[]).includes(lang) ? (lang as AuthLang) : "en";
  let v: string = AUTH_STRINGS[key]?.[l] ?? AUTH_STRINGS[key]?.en ?? "";
  if (vars) {
    v = v.replace(/\{(\w+)\}/g, (_m, k) => (k in vars ? String(vars[k]) : "{" + k + "}"));
  }
  return v;
}

/** Localized account/auth page path prefix. "" for en, otherwise "/<lang>". */
export function authLangPrefix(lang: string): string {
  return lang && lang !== "en" ? "/" + lang : "";
}
