// SOS floating widget i18n strings (12 languages)
export const SOS_STRINGS: Record<string, Record<string, string>> = {
  en: {
    sos: "SOS",
    translate: "Translate",
    gps: "GPS",
    embassy: "Embassy",
    contacts: "Contacts",
    culture: "Culture",
    location: "Location",
    close: "Close",
    emergencyNumbers: "Emergency Numbers",
    tapToCall: "Tap to call",
    tooltipTitle: "🆘 Emergency SOS",
    tooltipTap: "• Tap: Call Police (110)",
    tooltipMenu: "• Menu: Translation, GPS, Embassy, Culture",
    tooltipOffline: "Works offline",
    openMenu: "Open emergency menu",
    closeMenu: "Close emergency menu",
    sosAria: "SOS Emergency - Tap to call police",
    culturalTips: "Cultural Tips",
    culturalSub: "Important cultural awareness and local customs for your visit",
    viewWarnings: "View Cultural Warnings & Tips",
    tip1: "Respect local customs and traditions",
    tip2: "Learn basic etiquette for temples and public spaces",
    tip3: "Stay aware of regional regulations",
    ambulance: "Ambulance",
    police: "Police",
    fire: "Fire",
    traffic: "Traffic Accident",
  },
  ja: {
    sos: "SOS",
    translate: "翻訳",
    gps: "GPS",
    embassy: "大使館",
    contacts: "連絡先",
    culture: "文化",
    location: "位置情報",
    close: "閉じる",
    emergencyNumbers: "緊急連絡先",
    tapToCall: "タップして電話",
    tooltipTitle: "🆘 緊急SOS",
    tooltipTap: "• タップ：警察に電話 (110)",
    tooltipMenu: "• メニュー：翻訳、GPS、大使館、文化",
    tooltipOffline: "オフラインでも動作",
    openMenu: "緊急メニューを開く",
    closeMenu: "緊急メニューを閉じる",
    sosAria: "SOS緊急 - タップして警察に電話",
    culturalTips: "文化のヒント",
    culturalSub: "訪問中の重要な文化マナーと現地習慣",
    viewWarnings: "文化上の注意点とヒントを見る",
    tip1: "現地の習慣や伝統を尊重しましょう",
    tip2: "寺院や公共の場での基本的なマナーを学びましょう",
    tip3: "地域ごとの規制にも注意しましょう",
    ambulance: "救急車",
    police: "警察",
    fire: "消防",
    traffic: "交通事故",
  },
  ko: {
    sos: "SOS",
    translate: "번역",
    gps: "GPS",
    embassy: "대사관",
    contacts: "연락처",
    culture: "문화",
    location: "위치",
    close: "닫기",
    emergencyNumbers: "긴급 연락처",
    tapToCall: "탭하여 전화",
    tooltipTitle: "🆘 긴급 SOS",
    tooltipTap: "• 탭: 경찰에 전화 (110)",
    tooltipMenu: "• 메뉴: 번역, GPS, 대사관, 문화",
    tooltipOffline: "오프라인에서도 작동",
    openMenu: "긴급 메뉴 열기",
    closeMenu: "긴급 메뉴 닫기",
    sosAria: "SOS 긴급 - 탭하여 경찰에 전화",
    culturalTips: "문화 팁",
    culturalSub: "방문 중 중요한 문화 인식과 현지 관습",
    viewWarnings: "문화 경고 및 팁 보기",
    tip1: "현지 관습과 전통 존중",
    tip2: "사찰과 공공장소 기본 예절 배우기",
    tip3: "지역 규정 인지",
    ambulance: "구급차",
    police: "경찰",
    fire: "소방",
    traffic: "교통사고",
  },
  "zh-CN": {
    sos: "SOS",
    translate: "翻译",
    gps: "GPS",
    embassy: "大使馆",
    contacts: "联系人",
    culture: "文化",
    location: "位置",
    close: "关闭",
    emergencyNumbers: "紧急号码",
    tapToCall: "点击呼叫",
    tooltipTitle: "🆘 紧急SOS",
    tooltipTap: "• 点击: 呼叫警察 (110)",
    tooltipMenu: "• 菜单: 翻译、GPS、大使馆、文化",
    tooltipOffline: "离线可用",
    openMenu: "打开紧急菜单",
    closeMenu: "关闭紧急菜单",
    sosAria: "SOS紧急 - 点击呼叫警察",
    culturalTips: "文化提示",
    culturalSub: "访问期间重要的文化认知和当地习俗",
    viewWarnings: "查看文化警告与提示",
    tip1: "尊重当地习俗和传统",
    tip2: "学习寺庙和公共场所的基本礼仪",
    tip3: "注意当地法规",
    ambulance: "救护车",
    police: "警察",
    fire: "消防",
    traffic: "交通事故",
  },
  "zh-TW": {
    sos: "SOS",
    translate: "翻譯",
    gps: "GPS",
    embassy: "大使館",
    contacts: "聯絡人",
    culture: "文化",
    location: "位置",
    close: "關閉",
    emergencyNumbers: "緊急號碼",
    tapToCall: "點擊撥打",
    tooltipTitle: "🆘 緊急SOS",
    tooltipTap: "• 點擊: 呼叫警察 (110)",
    tooltipMenu: "• 選單: 翻譯、GPS、大使館、文化",
    tooltipOffline: "離線可用",
    openMenu: "開啟緊急選單",
    closeMenu: "關閉緊急選單",
    sosAria: "SOS緊急 - 點擊呼叫警察",
    culturalTips: "文化提示",
    culturalSub: "造訪期間重要的文化認知與當地習俗",
    viewWarnings: "查看文化警告與提示",
    tip1: "尊重當地習俗與傳統",
    tip2: "學習寺廟與公共場所的基本禮儀",
    tip3: "注意當地法規",
    ambulance: "救護車",
    police: "警察",
    fire: "消防",
    traffic: "交通事故",
  },
  th: {
    sos: "SOS",
    translate: "แปลภาษา",
    gps: "GPS",
    embassy: "สถานทูต",
    contacts: "ผู้ติดต่อ",
    culture: "วัฒนธรรม",
    location: "ตำแหน่ง",
    close: "ปิด",
    emergencyNumbers: "หมายเลขฉุกเฉิน",
    tapToCall: "แตะเพื่อโทร",
    tooltipTitle: "🆘 SOS ฉุกเฉิน",
    tooltipTap: "• แตะ: โทรหาตำรวจ (110)",
    tooltipMenu: "• เมนู: แปลภาษา, GPS, สถานทูต, วัฒนธรรม",
    tooltipOffline: "ใช้งานได้แม้ออฟไลน์",
    openMenu: "เปิดเมนูฉุกเฉิน",
    closeMenu: "ปิดเมนูฉุกเฉิน",
    sosAria: "SOS ฉุกเฉิน - แตะเพื่อโทรหาตำรวจ",
    culturalTips: "เคล็ดลับวัฒนธรรม",
    culturalSub: "การรับรู้วัฒนธรรมที่สำคัญและประเพณีท้องถิ่น",
    viewWarnings: "ดูคำเตือนและเคล็ดลับวัฒนธรรม",
    tip1: "เคารพประเพณีท้องถิ่น",
    tip2: "เรียนรู้มารยาทพื้นฐานในวัดและที่สาธารณะ",
    tip3: "ระวังกฎระเบียบท้องถิ่น",
    ambulance: "รถพยาบาล",
    police: "ตำรวจ",
    fire: "ดับเพลิง",
    traffic: "อุบัติเหตุจราจร",
  },
  vi: {
    sos: "SOS",
    translate: "Dịch",
    gps: "GPS",
    embassy: "Đại sứ quán",
    contacts: "Liên hệ",
    culture: "Văn hóa",
    location: "Vị trí",
    close: "Đóng",
    emergencyNumbers: "Số khẩn cấp",
    tapToCall: "Chạm để gọi",
    tooltipTitle: "🆘 SOS khẩn cấp",
    tooltipTap: "• Chạm: Gọi cảnh sát (110)",
    tooltipMenu: "• Menu: Dịch, GPS, Đại sứ quán, Văn hóa",
    tooltipOffline: "Hoạt động ngoại tuyến",
    openMenu: "Mở menu khẩn cấp",
    closeMenu: "Đóng menu khẩn cấp",
    sosAria: "SOS khẩn cấp - Chạm để gọi cảnh sát",
    culturalTips: "Mẹo văn hóa",
    culturalSub: "Nhận thức văn hóa quan trọng và phong tục địa phương",
    viewWarnings: "Xem cảnh báo và mẹo văn hóa",
    tip1: "Tôn trọng phong tục và truyền thống địa phương",
    tip2: "Học nghi thức cơ bản tại đền và nơi công cộng",
    tip3: "Lưu ý quy định khu vực",
    ambulance: "Xe cứu thương",
    police: "Cảnh sát",
    fire: "Cứu hỏa",
    traffic: "Tai nạn giao thông",
  },
  ru: {
    sos: "SOS",
    translate: "Перевод",
    gps: "GPS",
    embassy: "Посольство",
    contacts: "Контакты",
    culture: "Культура",
    location: "Местоположение",
    close: "Закрыть",
    emergencyNumbers: "Экстренные номера",
    tapToCall: "Нажмите, чтобы позвонить",
    tooltipTitle: "🆘 Экстренный SOS",
    tooltipTap: "• Нажмите: Позвонить в полицию (110)",
    tooltipMenu: "• Меню: Перевод, GPS, Посольство, Культура",
    tooltipOffline: "Работает офлайн",
    openMenu: "Открыть меню экстренной помощи",
    closeMenu: "Закрыть меню экстренной помощи",
    sosAria: "Экстренный SOS - нажмите, чтобы вызвать полицию",
    culturalTips: "Культурные советы",
    culturalSub: "Важные культурные особенности и местные обычаи",
    viewWarnings: "Посмотреть предупреждения и советы",
    tip1: "Уважайте местные обычаи",
    tip2: "Изучите базовый этикет в храмах и общественных местах",
    tip3: "Соблюдайте местные правила",
    ambulance: "Скорая помощь",
    police: "Полиция",
    fire: "Пожарная",
    traffic: "ДТП",
  },
  fr: {
    sos: "SOS",
    translate: "Traduire",
    gps: "GPS",
    embassy: "Ambassade",
    contacts: "Contacts",
    culture: "Culture",
    location: "Localisation",
    close: "Fermer",
    emergencyNumbers: "Numéros d'urgence",
    tapToCall: "Toucher pour appeler",
    tooltipTitle: "🆘 SOS d'urgence",
    tooltipTap: "• Toucher : Appeler la police (110)",
    tooltipMenu: "• Menu : Traduction, GPS, Ambassade, Culture",
    tooltipOffline: "Fonctionne hors ligne",
    openMenu: "Ouvrir le menu d'urgence",
    closeMenu: "Fermer le menu d'urgence",
    sosAria: "SOS d'urgence - toucher pour appeler la police",
    culturalTips: "Conseils culturels",
    culturalSub: "Sensibilisation culturelle importante et coutumes locales",
    viewWarnings: "Voir les avertissements et conseils",
    tip1: "Respectez les coutumes locales",
    tip2: "Apprenez l'étiquette de base dans les temples",
    tip3: "Restez informé des réglementations locales",
    ambulance: "Ambulance",
    police: "Police",
    fire: "Pompiers",
    traffic: "Accident de la route",
  },
  de: {
    sos: "SOS",
    translate: "Übersetzen",
    gps: "GPS",
    embassy: "Botschaft",
    contacts: "Kontakte",
    culture: "Kultur",
    location: "Standort",
    close: "Schließen",
    emergencyNumbers: "Notrufnummern",
    tapToCall: "Zum Anrufen tippen",
    tooltipTitle: "🆘 Notfall-SOS",
    tooltipTap: "• Tippen: Polizei anrufen (110)",
    tooltipMenu: "• Menü: Übersetzung, GPS, Botschaft, Kultur",
    tooltipOffline: "Funktioniert offline",
    openMenu: "Notfallmenü öffnen",
    closeMenu: "Notfallmenü schließen",
    sosAria: "Notfall-SOS - zum Anrufen der Polizei tippen",
    culturalTips: "Kulturelle Tipps",
    culturalSub: "Wichtige kulturelle Hinweise und lokale Bräuche",
    viewWarnings: "Warnungen und Tipps anzeigen",
    tip1: "Respektieren Sie lokale Bräuche",
    tip2: "Lernen Sie grundlegende Etikette in Tempeln",
    tip3: "Beachten Sie regionale Vorschriften",
    ambulance: "Krankenwagen",
    police: "Polizei",
    fire: "Feuerwehr",
    traffic: "Verkehrsunfall",
  },
  ar: {
    sos: "SOS",
    translate: "ترجمة",
    gps: "GPS",
    embassy: "سفارة",
    contacts: "جهات الاتصال",
    culture: "ثقافة",
    location: "الموقع",
    close: "إغلاق",
    emergencyNumbers: "أرقام الطوارئ",
    tapToCall: "اضغط للاتصال",
    tooltipTitle: "🆘 طوارئ SOS",
    tooltipTap: "• اضغط: اتصل بالشرطة (110)",
    tooltipMenu: "• القائمة: ترجمة، GPS، سفارة، ثقافة",
    tooltipOffline: "يعمل دون اتصال",
    openMenu: "فتح قائمة الطوارئ",
    closeMenu: "إغلاق قائمة الطوارئ",
    sosAria: "طوارئ SOS - اضغط للاتصال بالشرطة",
    culturalTips: "نصائح ثقافية",
    culturalSub: "الوعي الثقافي المهم والعادات المحلية",
    viewWarnings: "عرض التحذيرات والنصائح",
    tip1: "احترم العادات والتقاليد المحلية",
    tip2: "تعلم آداب المعابد والأماكن العامة",
    tip3: "انتبه للوائح المحلية",
    ambulance: "إسعاف",
    police: "شرطة",
    fire: "إطفاء",
    traffic: "حادث مرور",
  },
  fa: {
    sos: "SOS",
    translate: "ترجمه",
    gps: "GPS",
    embassy: "سفارت",
    contacts: "مخاطب‌ها",
    culture: "فرهنگ",
    location: "موقعیت",
    close: "بستن",
    emergencyNumbers: "شماره‌های اضطراری",
    tapToCall: "لمس برای تماس",
    tooltipTitle: "🆘 اضطراری SOS",
    tooltipTap: "• لمس: تماس با پلیس (110)",
    tooltipMenu: "• منو: ترجمه، GPS، سفارت، فرهنگ",
    tooltipOffline: "آفلاین نیز کار می‌کند",
    openMenu: "باز کردن منوی اضطراری",
    closeMenu: "بستن منوی اضطراری",
    sosAria: "اضطراری SOS - لمس برای تماس با پلیس",
    culturalTips: "نکات فرهنگی",
    culturalSub: "آگاهی فرهنگی مهم و آداب محلی",
    viewWarnings: "مشاهده هشدارها و نکات",
    tip1: "به آداب و رسوم محلی احترام بگذارید",
    tip2: "آداب پایه در معابد و اماکن عمومی",
    tip3: "به مقررات منطقه توجه کنید",
    ambulance: "آمبولانس",
    police: "پلیس",
    fire: "آتش‌نشانی",
    traffic: "تصادف رانندگی",
  },
};

export function useClientLang(): string {
  if (typeof window === "undefined") return "en";
  try {
    const stored = window.localStorage.getItem("chinaconnect_language");
    if (stored) return stored;
  } catch {}
  return document.documentElement.lang || "en";
}
