/**
 * AIChat UI labels — 12 languages, self-contained (mirrors the auth-strings pattern).
 */

export type AiChatLang =
  | "en"
  | "ja"
  | "ko"
  | "zh-CN"
  | "zh-TW"
  | "th"
  | "vi"
  | "ru"
  | "fr"
  | "de"
  | "ar"
  | "fa";

export interface AiChatLabels {
  placeholder: string;
  send: string;
  history: string;
  newChat: string;
  savedItineraries: string;
  noSavedItineraries: string;
  mcpOnline: string;
  mcpOffline: string;
  cancel: string;
  thinking: string;
  map: string;
  saveRoute: string;
  signInToSave: string;
  noRouteData: string;
  routeSaved: string;
  routeSaveFailed: string;
  whereToGo: string;
  intro: string;
  requestsRemaining: string;
  upgrade: string;
  monthlyLimitReached: string;
  upgradePlan: string;
  upgradeToContinue: string;
  aiDisclaimer: string;
  shareItinerary: string;
  shareCode: string;
  close: string;
  copyLink: string;
}

export const CHAT_LABELS: Record<AiChatLang, AiChatLabels> = {
  en: {
    placeholder: "Ask about your China trip...",
    send: "Send",
    history: "History",
    newChat: "New Chat",
    savedItineraries: "Saved Itineraries",
    noSavedItineraries: "No saved itineraries yet",
    mcpOnline: "AI Online",
    mcpOffline: "AI Offline",
    cancel: "Cancel",
    thinking: "Thinking...",
    map: "Map",
    saveRoute: "Save Route",
    signInToSave: "Please sign in to save routes.",
    noRouteData: "No route data to save.",
    routeSaved: "Route saved successfully!",
    routeSaveFailed: "Failed to save route: ",
    whereToGo: "Where do you want to go in China?",
    intro:
      "I can help you plan itineraries, recommend restaurants, and answer life questions. Try quick prompts or just ask!",
    requestsRemaining: "{n} AI requests remaining this month",
    upgrade: "Upgrade",
    monthlyLimitReached: "You've reached your monthly limit. Upgrade to continue.",
    upgradePlan: "Upgrade Plan",
    upgradeToContinue: "Upgrade to continue using AI...",
    aiDisclaimer: "AI responses are for reference only. Always verify locally.",
    shareItinerary: "Share Itinerary",
    shareCode: "Share Code:",
    close: "Close",
    copyLink: "Copy Link",
  },
  ja: {
    placeholder: "中国旅行について質問してください...",
    send: "送信",
    history: "履歴",
    newChat: "新しい会話",
    savedItineraries: "保存した旅程",
    noSavedItineraries: "保存した旅程はまだありません",
    mcpOnline: "AI オンライン",
    mcpOffline: "AI オフライン",
    cancel: "キャンセル",
    thinking: "考え中...",
    map: "地図",
    saveRoute: "旅程を保存",
    signInToSave: "旅程を保存するにはログインしてください。",
    noRouteData: "保存できる旅程データがありません。",
    routeSaved: "旅程を保存しました！",
    routeSaveFailed: "旅程の保存に失敗しました：",
    whereToGo: "中国のどこへ行きたいですか？",
    intro:
      "旅程の計画、グルメのおすすめ、生活の質問にお答えします。クイックプロンプトを試すか、直接質問してください！",
    requestsRemaining: "今月のAIリクエスト残り {n} 回",
    upgrade: "アップグレード",
    monthlyLimitReached: "今月のAIリクエスト上限に達しました。アップグレードして続行してください",
    upgradePlan: "プランをアップグレード",
    upgradeToContinue: "AIを続けて使うにはアップグレードしてください...",
    aiDisclaimer: "AIの回答は参考用です。現地の最新情報を必ず確認してください",
    shareItinerary: "旅程を共有",
    shareCode: "共有コード：",
    close: "閉じる",
    copyLink: "リンクをコピー",
  },
  ko: {
    placeholder: "중국 여행에 대해 물어보세요...",
    send: "보내기",
    history: "기록",
    newChat: "새 대화",
    savedItineraries: "저장된 일정",
    noSavedItineraries: "저장된 일정이 아직 없습니다",
    mcpOnline: "AI 온라인",
    mcpOffline: "AI 오프라인",
    cancel: "취소",
    thinking: "생각 중...",
    map: "지도",
    saveRoute: "일정 저장",
    signInToSave: "일정을 저장하려면 로그인하세요.",
    noRouteData: "저장할 일정 데이터가 없습니다.",
    routeSaved: "일정이 저장되었습니다!",
    routeSaveFailed: "일정 저장에 실패했습니다: ",
    whereToGo: "중국의 어디로 가고 싶으신가요?",
    intro:
      "여행 일정 계획, 맛집 추천, 생활 질문에 답변해 드립니다. 빠른 프롬프트를 시도하거나 직접 물어보세요!",
    requestsRemaining: "이번 달 AI 요청 {n}회 남음",
    upgrade: "업그레이드",
    monthlyLimitReached: "이번 달 AI 요청 한도에 도달했습니다. 업그레이드하여 계속하세요",
    upgradePlan: "요금제 업그레이드",
    upgradeToContinue: "AI를 계속 사용하려면 업그레이드하세요...",
    aiDisclaimer: "AI 답변은 참고용입니다. 현지 실제 정보를 꼭 확인하세요",
    shareItinerary: "일정 공유",
    shareCode: "공유 코드:",
    close: "닫기",
    copyLink: "링크 복사",
  },
  "zh-CN": {
    placeholder: "输入您的中国旅行问题...",
    send: "发送",
    history: "历史",
    newChat: "新建对话",
    savedItineraries: "已保存的行程",
    noSavedItineraries: "还没有保存的行程",
    mcpOnline: "AI 在线",
    mcpOffline: "AI 离线",
    cancel: "取消",
    thinking: "思考中...",
    map: "地图",
    saveRoute: "保存路线",
    signInToSave: "请登录后再保存路线。",
    noRouteData: "没有可保存的路线数据。",
    routeSaved: "路线保存成功！",
    routeSaveFailed: "保存路线失败：",
    whereToGo: "您想去中国的哪里？",
    intro: "我可以帮您规划行程、推荐美食、解答生活问题。试试快捷提示或直接问我！",
    requestsRemaining: "本月剩余 {n} 次AI请求",
    upgrade: "升级",
    monthlyLimitReached: "您已达到本月AI请求上限，请升级以继续使用",
    upgradePlan: "升级套餐",
    upgradeToContinue: "请升级以继续使用AI助手...",
    aiDisclaimer: "AI回复仅供参考，请以当地实际信息为准",
    shareItinerary: "分享行程",
    shareCode: "分享码：",
    close: "关闭",
    copyLink: "复制链接",
  },
  "zh-TW": {
    placeholder: "輸入您的中國旅行問題...",
    send: "傳送",
    history: "歷史",
    newChat: "新對話",
    savedItineraries: "已儲存的行程",
    noSavedItineraries: "還沒有儲存的行程",
    mcpOnline: "AI 在線",
    mcpOffline: "AI 離線",
    cancel: "取消",
    thinking: "思考中...",
    map: "地圖",
    saveRoute: "儲存路線",
    signInToSave: "請登入後再儲存路線。",
    noRouteData: "沒有可儲存的路線資料。",
    routeSaved: "路線儲存成功！",
    routeSaveFailed: "儲存路線失敗：",
    whereToGo: "您想去中國的哪裡？",
    intro: "我可以幫您規劃行程、推薦美食、解答生活問題。試試快捷提示或直接問我！",
    requestsRemaining: "本月剩餘 {n} 次AI請求",
    upgrade: "升級",
    monthlyLimitReached: "您已達到本月AI請求上限，請升級以繼續使用",
    upgradePlan: "升級方案",
    upgradeToContinue: "請升級以繼續使用AI助手...",
    aiDisclaimer: "AI回覆僅供參考，請以當地實際資訊為準",
    shareItinerary: "分享行程",
    shareCode: "分享碼：",
    close: "關閉",
    copyLink: "複製連結",
  },
  th: {
    placeholder: "ถามเกี่ยวกับการเดินทางจีนของคุณ...",
    send: "ส่ง",
    history: "ประวัติ",
    newChat: "แชทใหม่",
    savedItineraries: "แผนการเดินทางที่บันทึก",
    noSavedItineraries: "ยังไม่มีแผนการเดินทางที่บันทึก",
    mcpOnline: "AI ออนไลน์",
    mcpOffline: "AI ออฟไลน์",
    cancel: "ยกเลิก",
    thinking: "กำลังคิด...",
    map: "แผนที่",
    saveRoute: "บันทึกเส้นทาง",
    signInToSave: "กรุณาเข้าสู่ระบบเพื่อบันทึกเส้นทาง",
    noRouteData: "ไม่มีข้อมูลเส้นทางให้บันทึก",
    routeSaved: "บันทึกเส้นทางสำเร็จ!",
    routeSaveFailed: "บันทึกเส้นทางล้มเหลว: ",
    whereToGo: "คุณอยากไปที่ไหนในจีน?",
    intro: "ฉันช่วยวางแผนการเดินทาง แนะนำร้านอาหาร และตอบคำถามชีวิตได้ ลองใช้คำถามด่วนหรือถามฉันได้เลย!",
    requestsRemaining: "เหลือคำขอ AI {n} ครั้งในเดือนนี้",
    upgrade: "อัปเกรด",
    monthlyLimitReached: "คุณถึงขีดจำกัดคำขอ AI รายเดือนแล้ว อัปเกรดเพื่อใช้งานต่อ",
    upgradePlan: "อัปเกรดแพ็กเกจ",
    upgradeToContinue: "อัปเกรดเพื่อใช้ AI ต่อไป...",
    aiDisclaimer: "คำตอบจาก AI เป็นเพียงข้อมูลอ้างอิง โปรดตรวจสอบข้อมูลจริงในท้องถิ่น",
    shareItinerary: "แชร์แผนการเดินทาง",
    shareCode: "รหัสแชร์:",
    close: "ปิด",
    copyLink: "คัดลอกลิงก์",
  },
  vi: {
    placeholder: "Hỏi về chuyến đi Trung Quốc của bạn...",
    send: "Gửi",
    history: "Lịch sử",
    newChat: "Hội thoại mới",
    savedItineraries: "Hành trình đã lưu",
    noSavedItineraries: "Chưa có hành trình nào được lưu",
    mcpOnline: "AI trực tuyến",
    mcpOffline: "AI ngoại tuyến",
    cancel: "Hủy",
    thinking: "Đang suy nghĩ...",
    map: "Bản đồ",
    saveRoute: "Lưu hành trình",
    signInToSave: "Vui lòng đăng nhập để lưu hành trình.",
    noRouteData: "Không có dữ liệu hành trình để lưu.",
    routeSaved: "Đã lưu hành trình thành công!",
    routeSaveFailed: "Lưu hành trình thất bại: ",
    whereToGo: "Bạn muốn đi đâu ở Trung Quốc?",
    intro:
      "Tôi có thể giúp bạn lên kế hoạch hành trình, gợi ý ẩm thực và trả lời các câu hỏi cuộc sống. Hãy thử gợi ý nhanh hoặc hỏi trực tiếp!",
    requestsRemaining: "Còn {n} yêu cầu AI trong tháng này",
    upgrade: "Nâng cấp",
    monthlyLimitReached: "Bạn đã đạt giới hạn yêu cầu AI hàng tháng. Hãy nâng cấp để tiếp tục",
    upgradePlan: "Nâng cấp gói",
    upgradeToContinue: "Nâng cấp để tiếp tục sử dụng AI...",
    aiDisclaimer:
      "Câu trả lời của AI chỉ mang tính tham khảo. Luôn kiểm tra thông tin thực tế tại địa phương",
    shareItinerary: "Chia sẻ hành trình",
    shareCode: "Mã chia sẻ:",
    close: "Đóng",
    copyLink: "Sao chép liên kết",
  },
  ru: {
    placeholder: "Спросите о поездке в Китай...",
    send: "Отправить",
    history: "История",
    newChat: "Новый чат",
    savedItineraries: "Сохранённые маршруты",
    noSavedItineraries: "Сохранённых маршрутов пока нет",
    mcpOnline: "ИИ онлайн",
    mcpOffline: "ИИ офлайн",
    cancel: "Отмена",
    thinking: "Думаю...",
    map: "Карта",
    saveRoute: "Сохранить маршрут",
    signInToSave: "Войдите, чтобы сохранять маршруты.",
    noRouteData: "Нет данных маршрута для сохранения.",
    routeSaved: "Маршрут сохранён!",
    routeSaveFailed: "Не удалось сохранить маршрут: ",
    whereToGo: "Куда вы хотите поехать в Китае?",
    intro:
      "Я помогу спланировать маршрут, порекомендую рестораны и отвечу на вопросы о жизни. Попробуйте быстрые подсказки или спросите напрямую!",
    requestsRemaining: "Осталось {n} запросов ИИ в этом месяце",
    upgrade: "Обновить",
    monthlyLimitReached:
      "Вы достигли месячного лимита запросов ИИ. Обновите тариф, чтобы продолжить",
    upgradePlan: "Обновить тариф",
    upgradeToContinue: "Обновите тариф, чтобы продолжить использование ИИ...",
    aiDisclaimer:
      "Ответы ИИ носят справочный характер. Всегда проверяйте актуальную информацию на месте",
    shareItinerary: "Поделиться маршрутом",
    shareCode: "Код доступа:",
    close: "Закрыть",
    copyLink: "Копировать ссылку",
  },
  fr: {
    placeholder: "Posez une question sur votre voyage en Chine...",
    send: "Envoyer",
    history: "Historique",
    newChat: "Nouvelle discussion",
    savedItineraries: "Itinéraires enregistrés",
    noSavedItineraries: "Aucun itinéraire enregistré pour le moment",
    mcpOnline: "IA en ligne",
    mcpOffline: "IA hors ligne",
    cancel: "Annuler",
    thinking: "Réflexion...",
    map: "Carte",
    saveRoute: "Enregistrer l'itinéraire",
    signInToSave: "Veuillez vous connecter pour enregistrer des itinéraires.",
    noRouteData: "Aucune donnée d'itinéraire à enregistrer.",
    routeSaved: "Itinéraire enregistré avec succès !",
    routeSaveFailed: "Échec de l'enregistrement de l'itinéraire : ",
    whereToGo: "Où voulez-vous aller en Chine ?",
    intro:
      "Je peux vous aider à planifier des itinéraires, recommander des restaurants et répondre à vos questions pratiques. Essayez les invites rapides ou demandez-moi directement !",
    requestsRemaining: "{n} requêtes IA restantes ce mois-ci",
    upgrade: "Mettre à niveau",
    monthlyLimitReached:
      "Vous avez atteint votre limite mensuelle de requêtes IA. Mettez à niveau pour continuer",
    upgradePlan: "Mettre à niveau",
    upgradeToContinue: "Mettez à niveau pour continuer à utiliser l'IA...",
    aiDisclaimer:
      "Les réponses de l'IA sont fournies à titre indicatif. Vérifiez toujours les informations locales",
    shareItinerary: "Partager l'itinéraire",
    shareCode: "Code de partage :",
    close: "Fermer",
    copyLink: "Copier le lien",
  },
  de: {
    placeholder: "Fragen Sie nach Ihrer China-Reise...",
    send: "Senden",
    history: "Verlauf",
    newChat: "Neuer Chat",
    savedItineraries: "Gespeicherte Reiserouten",
    noSavedItineraries: "Noch keine gespeicherten Reiserouten",
    mcpOnline: "KI online",
    mcpOffline: "KI offline",
    cancel: "Abbrechen",
    thinking: "Denke nach...",
    map: "Karte",
    saveRoute: "Route speichern",
    signInToSave: "Bitte melden Sie sich an, um Routen zu speichern.",
    noRouteData: "Keine Routendaten zum Speichern.",
    routeSaved: "Route erfolgreich gespeichert!",
    routeSaveFailed: "Speichern der Route fehlgeschlagen: ",
    whereToGo: "Wohin möchten Sie in China reisen?",
    intro:
      "Ich kann Reiserouten planen, Restaurants empfehlen und Alltagsfragen beantworten. Probieren Sie die Schnellvorschläge oder fragen Sie direkt!",
    requestsRemaining: "Noch {n} KI-Anfragen diesen Monat",
    upgrade: "Upgraden",
    monthlyLimitReached:
      "Sie haben Ihr monatliches KI-Limit erreicht. Bitte upgraden Sie, um fortzufahren",
    upgradePlan: "Plan upgraden",
    upgradeToContinue: "Upgraden Sie, um die KI weiter zu nutzen...",
    aiDisclaimer:
      "KI-Antworten dienen nur zur Referenz. Prüfen Sie immer die lokalen Informationen",
    shareItinerary: "Reiseroute teilen",
    shareCode: "Freigabecode:",
    close: "Schließen",
    copyLink: "Link kopieren",
  },
  ar: {
    placeholder: "اسأل عن رحلتك إلى الصين...",
    send: "إرسال",
    history: "السجل",
    newChat: "محادثة جديدة",
    savedItineraries: "الرحلات المحفوظة",
    noSavedItineraries: "لا توجد رحلات محفوظة بعد",
    mcpOnline: "الذكاء الاصطناعي متصل",
    mcpOffline: "الذكاء الاصطناعي غير متصل",
    cancel: "إلغاء",
    thinking: "جارٍ التفكير...",
    map: "الخريطة",
    saveRoute: "حفظ المسار",
    signInToSave: "يرجى تسجيل الدخول لحفظ المسارات.",
    noRouteData: "لا توجد بيانات مسار للحفظ.",
    routeSaved: "تم حفظ المسار بنجاح!",
    routeSaveFailed: "فشل حفظ المسار: ",
    whereToGo: "إلى أين تريد الذهاب في الصين؟",
    intro:
      "يمكنني مساعدتك في تخطيط الرحلات وتقديم توصيات المطاعم والإجابة عن أسئلة الحياة. جرب الاقتراحات السريعة أو اسأل مباشرة!",
    requestsRemaining: "متبقي {n} طلبات ذكاء اصطناعي هذا الشهر",
    upgrade: "ترقية",
    monthlyLimitReached: "لقد وصلت إلى الحد الشهري لطلبات الذكاء الاصطناعي. قم بالترقية للمتابعة",
    upgradePlan: "ترقية الخطة",
    upgradeToContinue: "قم بالترقية لمواصلة استخدام الذكاء الاصطناعي...",
    aiDisclaimer: "إجابات الذكاء الاصطناعي للرجوع إليها فقط. تحقق دائماً من المعلومات المحلية",
    shareItinerary: "مشاركة الرحلة",
    shareCode: "رمز المشاركة:",
    close: "إغلاق",
    copyLink: "نسخ الرابط",
  },
  fa: {
    placeholder: "درباره سفرتان به چین بپرسید...",
    send: "ارسال",
    history: "تاریخچه",
    newChat: "گفتگوی جدید",
    savedItineraries: "مسیرهای ذخیره‌شده",
    noSavedItineraries: "هنوز مسیر ذخیره‌شده‌ای وجود ندارد",
    mcpOnline: "هوش مصنوعی آنلاین",
    mcpOffline: "هوش مصنوعی آفلاین",
    cancel: "لغو",
    thinking: "در حال فکر کردن...",
    map: "نقشه",
    saveRoute: "ذخیره مسیر",
    signInToSave: "برای ذخیره مسیر لطفاً وارد شوید.",
    noRouteData: "داده‌ای برای ذخیره مسیر وجود ندارد.",
    routeSaved: "مسیر با موفقیت ذخیره شد!",
    routeSaveFailed: "ذخیره مسیر ناموفق بود: ",
    whereToGo: "کجا در چین می‌خواهید بروید؟",
    intro:
      "می‌توانم به برنامه‌ریزی سفر، پیشنهاد رستوران و پاسخ به سؤالات زندگی کمک کنم. پیشنهادهای سریع را امتحان کنید یا مستقیم بپرسید!",
    requestsRemaining: "{n} درخواست هوش مصنوعی باقی‌مانده در این ماه",
    upgrade: "ارتقا",
    monthlyLimitReached: "به سقف ماهانه درخواست‌های هوش مصنوعی رسیده‌اید. برای ادامه ارتقا دهید",
    upgradePlan: "ارتقای طرح",
    upgradeToContinue: "برای ادامه استفاده از هوش مصنوعی ارتقا دهید...",
    aiDisclaimer: "پاسخ‌های هوش مصنوعی فقط جنبه مرجع دارند. همیشه اطلاعات واقعی محلی را بررسی کنید",
    shareItinerary: "اشتراک‌گذاری سفر",
    shareCode: "کد اشتراک‌گذاری:",
    close: "بستن",
    copyLink: "کپی لینک",
  },
};
