/**
 * AIChat UI labels — 12 languages, self-contained (mirrors the auth-strings pattern).
 */

export type AiChatLang =
  | "en"
  | "ja"
  | "ko"
  | "zh-CN"
  | "zh-TW"
  | "th"
  | "vi"
  | "ru"
  | "fr"
  | "de"
  | "ar"
  | "fa";

export interface AiChatLabels {
  placeholder: string;
  send: string;
  history: string;
  newChat: string;
  savedItineraries: string;
  noSavedItineraries: string;
  mcpOnline: string;
  mcpOffline: string;
  cancel: string;
  thinking: string;
  saving: string;
  map: string;
  saveRoute: string;
  signInToSave: string;
  noRouteData: string;
  routeSaved: string;
  routeSaveFailed: string;
  whereToGo: string;
  intro: string;
  requestsRemaining: string;
  upgrade: string;
  monthlyLimitReached: string;
  upgradePlan: string;
  upgradeToContinue: string;
  aiDisclaimer: string;
  firstUseNotice: string;
  shareItinerary: string;
  shareCode: string;
  close: string;
  copyLink: string;
  conversations: string;
  itineraries: string;
  newChatButton: string;
  noConversationsYet: string;
  justNow: string;
  days: string;
  deleteTitle: string;
  deleteConfirm: string;
  itineraryReady: string;
  saveItineraryNow: string;
  notNow: string;
  saveItineraryTitle: string;
  itineraryName: string;
  savedNotice: string;
  pdfExportFailed: string;
}

export const CHAT_LABELS: Record<AiChatLang, AiChatLabels> = {
  en: {
    placeholder: "Ask about your China trip...",
    send: "Send",
    history: "History",
    newChat: "New Chat",
    savedItineraries: "Saved Itineraries",
    noSavedItineraries: "No saved itineraries yet",
    mcpOnline: "AI Online",
    mcpOffline: "AI Offline",
    cancel: "Cancel",
    thinking: "Thinking...",
    saving: "Saving...",
    map: "Map",
    saveRoute: "Save Route",
    signInToSave: "Please sign in to save routes.",
    noRouteData: "No route data to save.",
    routeSaved: "Route saved successfully!",
    routeSaveFailed: "Failed to save route: ",
    whereToGo: "Where do you want to go in China?",
    intro:
      "I can help you plan itineraries, recommend restaurants, and answer life questions. Try quick prompts or just ask!",
    requestsRemaining: "{n} AI requests remaining this month",
    upgrade: "Upgrade",
    monthlyLimitReached: "You've reached your monthly limit. Upgrade to continue.",
    upgradePlan: "Upgrade Plan",
    upgradeToContinue: "Upgrade to continue using AI...",
    aiDisclaimer: "AI responses are for reference only. Always verify locally.",
    firstUseNotice: "When you ask for a detailed itinerary, the AI searches live and plans in real time. First-time requests can take a few minutes — usually no more than 5 minutes. Please wait patiently.",
    shareItinerary: "Share Itinerary",
    shareCode: "Share Code:",
    close: "Close",
    copyLink: "Copy Link",
    conversations: "Conversations",
    itineraries: "Itineraries",
    newChatButton: "New Chat",
    noConversationsYet: "No conversations yet",
    justNow: "Just now",
    days: "days",
    deleteTitle: "Delete",
    deleteConfirm: "Delete this conversation?",
    itineraryReady: "Your itinerary is ready - save it to keep it forever.",
    saveItineraryNow: "Save this itinerary",
    notNow: "Not now",
    saveItineraryTitle: "Save Itinerary",
    itineraryName: "Itinerary name",
    savedNotice: "Itinerary saved!",
    pdfExportFailed: "PDF export failed. Please try again.",

  },
  ja: {
    placeholder: "中国旅行について質問してください...",
    send: "送信",
    history: "履歴",
    newChat: "新しい会話",
    savedItineraries: "保存した旅程",
    noSavedItineraries: "保存した旅程はまだありません",
    mcpOnline: "AI オンライン",
    mcpOffline: "AI オフライン",
    cancel: "キャンセル",
    thinking: "考え中...",
    saving: "保存中...",
    map: "地図",
    saveRoute: "旅程を保存",
    signInToSave: "旅程を保存するにはログインしてください。",
    noRouteData: "保存できる旅程データがありません。",
    routeSaved: "旅程を保存しました！",
    routeSaveFailed: "旅程の保存に失敗しました：",
    whereToGo: "中国のどこへ行きたいですか？",
    intro:
      "旅程の計画、グルメのおすすめ、生活の質問にお答えします。クイックプロンプトを試すか、直接質問してください！",
    requestsRemaining: "今月のAIリクエスト残り {n} 回",
    upgrade: "アップグレード",
    monthlyLimitReached: "今月のAIリクエスト上限に達しました。アップグレードして続行してください",
    upgradePlan: "プランをアップグレード",
    upgradeToContinue: "AIを続けて使うにはアップグレードしてください...",
    aiDisclaimer: "AIの回答は参考用です。現地の最新情報を必ず確認してください",
    firstUseNotice: "初めてAIで詳細な旅程を計画する場合、AIがリアルタイムに検索・処理するため時間がかかります。通常5分以内ですので、しばらくお待ちください。",
    shareItinerary: "旅程を共有",
    shareCode: "共有コード：",
    close: "閉じる",
    copyLink: "リンクをコピー",
    conversations: "会話",
    itineraries: "旅程",
    newChatButton: "新しいチャット",
    noConversationsYet: "まだ会話がありません",
    justNow: "たった今",
    days: "日",
    deleteTitle: "削除",
    deleteConfirm: "この会話を削除しますか？",
    itineraryReady: "旅程が完成しました - 保存していつでも見返せます。",
    saveItineraryNow: "この旅程を保存",
    notNow: "あとで",
    saveItineraryTitle: "旅程を保存",
    itineraryName: "旅程名",
    savedNotice: "旅程を保存しました！",
    pdfExportFailed: "PDFの出力に失敗しました。もう一度お試しください。",

  },
  ko: {
    placeholder: "중국 여행에 대해 물어보세요...",
    send: "보내기",
    history: "기록",
    newChat: "새 대화",
    savedItineraries: "저장된 일정",
    noSavedItineraries: "저장된 일정이 아직 없습니다",
    mcpOnline: "AI 온라인",
    mcpOffline: "AI 오프라인",
    cancel: "취소",
    thinking: "생각 중...",
    saving: "저장 중...",
    map: "지도",
    saveRoute: "일정 저장",
    signInToSave: "일정을 저장하려면 로그인하세요.",
    noRouteData: "저장할 일정 데이터가 없습니다.",
    routeSaved: "일정이 저장되었습니다!",
    routeSaveFailed: "일정 저장에 실패했습니다: ",
    whereToGo: "중국의 어디로 가고 싶으신가요?",
    intro:
      "여행 일정 계획, 맛집 추천, 생활 질문에 답변해 드립니다. 빠른 프롬프트를 시도하거나 직접 물어보세요!",
    requestsRemaining: "이번 달 AI 요청 {n}회 남음",
    upgrade: "업그레이드",
    monthlyLimitReached: "이번 달 AI 요청 한도에 도달했습니다. 업그레이드하여 계속하세요",
    upgradePlan: "요금제 업그레이드",
    upgradeToContinue: "AI를 계속 사용하려면 업그레이드하세요...",
    aiDisclaimer: "AI 답변은 참고용입니다. 현지 실제 정보를 꼭 확인하세요",
    firstUseNotice: "AI로 상세 일정을 처음 계획할 때는 실시간 검색과 처리를 위해 시간이 걸립니다. 보통 5분을 넘지 않으니 잠시만 기다려 주세요.",
    shareItinerary: "일정 공유",
    shareCode: "공유 코드:",
    close: "닫기",
    copyLink: "링크 복사",
    conversations: "대화",
    itineraries: "일정",
    newChatButton: "새 대화",
    noConversationsYet: "아직 대화가 없습니다",
    justNow: "방금 전",
    days: "일",
    deleteTitle: "삭제",
    deleteConfirm: "이 대화를 삭제하시겠습니까?",
    itineraryReady: "여행 일정이 완성되었습니다 - 저장해 두면 언제든 다시 볼 수 있습니다.",
    saveItineraryNow: "이 일정 저장",
    notNow: "나중에",
    saveItineraryTitle: "일정 저장",
    itineraryName: "일정 이름",
    savedNotice: "일정이 저장되었습니다!",
    pdfExportFailed: "PDF 내보내기에 실패했습니다. 다시 시도해 주세요.",

  },
  "zh-CN": {
    placeholder: "输入您的中国旅行问题...",
    send: "发送",
    history: "历史",
    newChat: "新建对话",
    savedItineraries: "已保存的行程",
    noSavedItineraries: "还没有保存的行程",
    mcpOnline: "AI 在线",
    mcpOffline: "AI 离线",
    cancel: "取消",
    thinking: "思考中...",
    saving: "保存中...",
    map: "地图",
    saveRoute: "保存路线",
    signInToSave: "请登录后再保存路线。",
    noRouteData: "没有可保存的路线数据。",
    routeSaved: "路线保存成功！",
    routeSaveFailed: "保存路线失败：",
    whereToGo: "您想去中国的哪里？",
    intro: "我可以帮您规划行程、推荐美食、解答生活问题。试试快捷提示或直接问我！",
    requestsRemaining: "本月剩余 {n} 次AI请求",
    upgrade: "升级",
    monthlyLimitReached: "您已达到本月AI请求上限，请升级以继续使用",
    upgradePlan: "升级套餐",
    upgradeToContinue: "请升级以继续使用AI助手...",
    aiDisclaimer: "AI回复仅供参考，请以当地实际信息为准",
    firstUseNotice: "首次使用AI规划详细内容时，AI需要联网搜索并长时间思考和处理，等待时间较长，通常不会超过5分钟，请耐心等待。",
    shareItinerary: "分享行程",
    shareCode: "分享码：",
    close: "关闭",
    copyLink: "复制链接",
    conversations: "对话记录",
    itineraries: "行程",
    newChatButton: "新建对话",
    noConversationsYet: "还没有对话",
    justNow: "刚刚",
    days: "天",
    deleteTitle: "删除",
    deleteConfirm: "删除这个对话？",
    itineraryReady: "行程已生成 - 保存后随时可以查看。",
    saveItineraryNow: "保存这个行程",
    notNow: "暂不保存",
    saveItineraryTitle: "保存行程",
    itineraryName: "行程名称",
    savedNotice: "行程已保存！",
    pdfExportFailed: "PDF 导出失败，请重试。",

  },
  "zh-TW": {
    placeholder: "輸入您的中國旅行問題...",
    send: "傳送",
    history: "歷史",
    newChat: "新對話",
    savedItineraries: "已儲存的行程",
    noSavedItineraries: "還沒有儲存的行程",
    mcpOnline: "AI 在線",
    mcpOffline: "AI 離線",
    cancel: "取消",
    thinking: "思考中...",
    saving: "儲存中...",
    map: "地圖",
    saveRoute: "儲存路線",
    signInToSave: "請登入後再儲存路線。",
    noRouteData: "沒有可儲存的路線資料。",
    routeSaved: "路線儲存成功！",
    routeSaveFailed: "儲存路線失敗：",
    whereToGo: "您想去中國的哪裡？",
    intro: "我可以幫您規劃行程、推薦美食、解答生活問題。試試快捷提示或直接問我！",
    requestsRemaining: "本月剩餘 {n} 次AI請求",
    upgrade: "升級",
    monthlyLimitReached: "您已達到本月AI請求上限，請升級以繼續使用",
    upgradePlan: "升級方案",
    upgradeToContinue: "請升級以繼續使用AI助手...",
    aiDisclaimer: "AI回覆僅供參考，請以當地實際資訊為準",
    firstUseNotice: "首次使用AI規劃詳細內容時，AI需要聯網搜尋並長時間思考與處理，等待時間較長，通常不會超過5分鐘，請耐心等待。",
    shareItinerary: "分享行程",
    shareCode: "分享碼：",
    close: "關閉",
    copyLink: "複製連結",
    conversations: "對話記錄",
    itineraries: "行程",
    newChatButton: "新對話",
    noConversationsYet: "還沒有對話",
    justNow: "剛剛",
    days: "天",
    deleteTitle: "刪除",
    deleteConfirm: "刪除這個對話？",
    itineraryReady: "行程已生成 - 儲存後隨時可以查看。",
    saveItineraryNow: "儲存這個行程",
    notNow: "暫不儲存",
    saveItineraryTitle: "儲存行程",
    itineraryName: "行程名稱",
    savedNotice: "行程已儲存！",
    pdfExportFailed: "PDF 匯出失敗，請重試。",

  },
  th: {
    placeholder: "ถามเกี่ยวกับการเดินทางจีนของคุณ...",
    send: "ส่ง",
    history: "ประวัติ",
    newChat: "แชทใหม่",
    savedItineraries: "แผนการเดินทางที่บันทึก",
    noSavedItineraries: "ยังไม่มีแผนการเดินทางที่บันทึก",
    mcpOnline: "AI ออนไลน์",
    mcpOffline: "AI ออฟไลน์",
    cancel: "ยกเลิก",
    thinking: "กำลังคิด...",
    saving: "กำลังบันทึก...",
    map: "แผนที่",
    saveRoute: "บันทึกเส้นทาง",
    signInToSave: "กรุณาเข้าสู่ระบบเพื่อบันทึกเส้นทาง",
    noRouteData: "ไม่มีข้อมูลเส้นทางให้บันทึก",
    routeSaved: "บันทึกเส้นทางสำเร็จ!",
    routeSaveFailed: "บันทึกเส้นทางล้มเหลว: ",
    whereToGo: "คุณอยากไปที่ไหนในจีน?",
    intro: "ฉันช่วยวางแผนการเดินทาง แนะนำร้านอาหาร และตอบคำถามชีวิตได้ ลองใช้คำถามด่วนหรือถามฉันได้เลย!",
    requestsRemaining: "เหลือคำขอ AI {n} ครั้งในเดือนนี้",
    upgrade: "อัปเกรด",
    monthlyLimitReached: "คุณถึงขีดจำกัดคำขอ AI รายเดือนแล้ว อัปเกรดเพื่อใช้งานต่อ",
    upgradePlan: "อัปเกรดแพ็กเกจ",
    upgradeToContinue: "อัปเกรดเพื่อใช้ AI ต่อไป...",
    aiDisclaimer: "คำตอบจาก AI เป็นเพียงข้อมูลอ้างอิง โปรดตรวจสอบข้อมูลจริงในท้องถิ่น",
    firstUseNotice: "เมื่อใช้ AI วางแผนรายละเอียดครั้งแรก AI จะค้นหาและประมวลผลแบบเรียลไทม์ อาจใช้เวลาสักครู่ โดยปกติไม่เกิน 5 นาที กรุณารอสักครู่",
    shareItinerary: "แชร์แผนการเดินทาง",
    shareCode: "รหัสแชร์:",
    close: "ปิด",
    copyLink: "คัดลอกลิงก์",
    conversations: "การสนทนา",
    itineraries: "แผนการเดินทาง",
    newChatButton: "แชทใหม่",
    noConversationsYet: "ยังไม่มีการสนทนา",
    justNow: "เมื่อสักครู่",
    days: "วัน",
    deleteTitle: "ลบ",
    deleteConfirm: "ลบการสนทนานี้หรือไม่",
    itineraryReady: "แผนการเดินทางพร้อมแล้ว - บันทึกไว้เพื่อดูได้ตลอด",
    saveItineraryNow: "บันทึกแผนนี้",
    notNow: "ไม่ตอนนี้",
    saveItineraryTitle: "บันทึกแผนการเดินทาง",
    itineraryName: "ชื่อแผน",
    savedNotice: "บันทึกแผนแล้ว!",
    pdfExportFailed: "การส่งออก PDF ล้มเหลว กรุณาลองอีกครั้ง",

  },
  vi: {
    placeholder: "Hỏi về chuyến đi Trung Quốc của bạn...",
    send: "Gửi",
    history: "Lịch sử",
    newChat: "Hội thoại mới",
    savedItineraries: "Hành trình đã lưu",
    noSavedItineraries: "Chưa có hành trình nào được lưu",
    mcpOnline: "AI trực tuyến",
    mcpOffline: "AI ngoại tuyến",
    cancel: "Hủy",
    thinking: "Đang suy nghĩ...",
    saving: "Đang lưu...",
    map: "Bản đồ",
    saveRoute: "Lưu hành trình",
    signInToSave: "Vui lòng đăng nhập để lưu hành trình.",
    noRouteData: "Không có dữ liệu hành trình để lưu.",
    routeSaved: "Đã lưu hành trình thành công!",
    routeSaveFailed: "Lưu hành trình thất bại: ",
    whereToGo: "Bạn muốn đi đâu ở Trung Quốc?",
    intro:
      "Tôi có thể giúp bạn lên kế hoạch hành trình, gợi ý ẩm thực và trả lời các câu hỏi cuộc sống. Hãy thử gợi ý nhanh hoặc hỏi trực tiếp!",
    requestsRemaining: "Còn {n} yêu cầu AI trong tháng này",
    upgrade: "Nâng cấp",
    monthlyLimitReached: "Bạn đã đạt giới hạn yêu cầu AI hàng tháng. Hãy nâng cấp để tiếp tục",
    upgradePlan: "Nâng cấp gói",
    upgradeToContinue: "Nâng cấp để tiếp tục sử dụng AI...",
    aiDisclaimer:
      "Câu trả lời của AI chỉ mang tính tham khảo. Luôn kiểm tra thông tin thực tế tại địa phương",
    firstUseNotice: "Khi dùng AI lập kế hoạch chi tiết lần đầu, AI sẽ tìm kiếm và xử lý theo thời gian thực nên cần chờ lâu hơn, thường không quá 5 phút. Vui lòng kiên nhẫn chờ đợi.",
    shareItinerary: "Chia sẻ hành trình",
    shareCode: "Mã chia sẻ:",
    close: "Đóng",
    copyLink: "Sao chép liên kết",
    conversations: "Hội thoại",
    itineraries: "Hành trình",
    newChatButton: "Hội thoại mới",
    noConversationsYet: "Chưa có hội thoại nào",
    justNow: "Vừa xong",
    days: "ngày",
    deleteTitle: "Xóa",
    deleteConfirm: "Xóa hội thoại này?",
    itineraryReady: "Hành trình của bạn đã sẵn sàng - hãy lưu để xem lại bất cứ lúc nào.",
    saveItineraryNow: "Lưu hành trình này",
    notNow: "Để sau",
    saveItineraryTitle: "Lưu hành trình",
    itineraryName: "Tên hành trình",
    savedNotice: "Đã lưu hành trình!",
    pdfExportFailed: "Xuất PDF thất bại. Vui lòng thử lại.",

  },
  ru: {
    placeholder: "Спросите о поездке в Китай...",
    send: "Отправить",
    history: "История",
    newChat: "Новый чат",
    savedItineraries: "Сохранённые маршруты",
    noSavedItineraries: "Сохранённых маршрутов пока нет",
    mcpOnline: "ИИ онлайн",
    mcpOffline: "ИИ офлайн",
    cancel: "Отмена",
    thinking: "Думаю...",
    saving: "Сохранение...",
    map: "Карта",
    saveRoute: "Сохранить маршрут",
    signInToSave: "Войдите, чтобы сохранять маршруты.",
    noRouteData: "Нет данных маршрута для сохранения.",
    routeSaved: "Маршрут сохранён!",
    routeSaveFailed: "Не удалось сохранить маршрут: ",
    whereToGo: "Куда вы хотите поехать в Китае?",
    intro:
      "Я помогу спланировать маршрут, порекомендую рестораны и отвечу на вопросы о жизни. Попробуйте быстрые подсказки или спросите напрямую!",
    requestsRemaining: "Осталось {n} запросов ИИ в этом месяце",
    upgrade: "Обновить",
    monthlyLimitReached:
      "Вы достигли месячного лимита запросов ИИ. Обновите тариф, чтобы продолжить",
    upgradePlan: "Обновить тариф",
    upgradeToContinue: "Обновите тариф, чтобы продолжить использование ИИ...",
    aiDisclaimer:
      "Ответы ИИ носят справочный характер. Всегда проверяйте актуальную информацию на месте",
    firstUseNotice: "При первом использовании ИИ для детального планирования требуется время на поиск и обработку данных в реальном времени. Обычно это занимает не более 5 минут. Пожалуйста, подождите.",
    shareItinerary: "Поделиться маршрутом",
    shareCode: "Код доступа:",
    close: "Закрыть",
    copyLink: "Копировать ссылку",
    conversations: "Диалоги",
    itineraries: "Маршруты",
    newChatButton: "Новый чат",
    noConversationsYet: "Диалогов пока нет",
    justNow: "Только что",
    days: "дней",
    deleteTitle: "Удалить",
    deleteConfirm: "Удалить этот диалог?",
    itineraryReady: "Ваш маршрут готов - сохраните его, чтобы возвращаться к нему в любое время.",
    saveItineraryNow: "Сохранить маршрут",
    notNow: "Не сейчас",
    saveItineraryTitle: "Сохранить маршрут",
    itineraryName: "Название маршрута",
    savedNotice: "Маршрут сохранён!",
    pdfExportFailed: "Не удалось экспортировать PDF. Попробуйте ещё раз.",

  },
  fr: {
    placeholder: "Posez une question sur votre voyage en Chine...",
    send: "Envoyer",
    history: "Historique",
    newChat: "Nouvelle discussion",
    savedItineraries: "Itinéraires enregistrés",
    noSavedItineraries: "Aucun itinéraire enregistré pour le moment",
    mcpOnline: "IA en ligne",
    mcpOffline: "IA hors ligne",
    cancel: "Annuler",
    thinking: "Réflexion...",
    saving: "Enregistrement...",
    map: "Carte",
    saveRoute: "Enregistrer l'itinéraire",
    signInToSave: "Veuillez vous connecter pour enregistrer des itinéraires.",
    noRouteData: "Aucune donnée d'itinéraire à enregistrer.",
    routeSaved: "Itinéraire enregistré avec succès !",
    routeSaveFailed: "Échec de l'enregistrement de l'itinéraire : ",
    whereToGo: "Où voulez-vous aller en Chine ?",
    intro:
      "Je peux vous aider à planifier des itinéraires, recommander des restaurants et répondre à vos questions pratiques. Essayez les invites rapides ou demandez-moi directement !",
    requestsRemaining: "{n} requêtes IA restantes ce mois-ci",
    upgrade: "Mettre à niveau",
    monthlyLimitReached:
      "Vous avez atteint votre limite mensuelle de requêtes IA. Mettez à niveau pour continuer",
    upgradePlan: "Mettre à niveau",
    upgradeToContinue: "Mettez à niveau pour continuer à utiliser l'IA...",
    aiDisclaimer:
      "Les réponses de l'IA sont fournies à titre indicatif. Vérifiez toujours les informations locales",
    firstUseNotice: "Lors de la première utilisation de l'IA pour planifier en détail, l'IA recherche et traite en temps réel. L'attente peut être longue, généralement pas plus de 5 minutes. Merci de patienter.",
    shareItinerary: "Partager l'itinéraire",
    shareCode: "Code de partage :",
    close: "Fermer",
    copyLink: "Copier le lien",
    conversations: "Conversations",
    itineraries: "Itinéraires",
    newChatButton: "Nouvelle discussion",
    noConversationsYet: "Aucune discussion",
    justNow: "À l'instant",
    days: "jours",
    deleteTitle: "Supprimer",
    deleteConfirm: "Supprimer cette discussion ?",
    itineraryReady: "Votre itinéraire est prêt - enregistrez-le pour le retrouver à tout moment.",
    saveItineraryNow: "Enregistrer cet itinéraire",
    notNow: "Plus tard",
    saveItineraryTitle: "Enregistrer l'itinéraire",
    itineraryName: "Nom de l'itinéraire",
    savedNotice: "Itinéraire enregistré !",
    pdfExportFailed: "Échec de l'export PDF. Veuillez réessayer.",

  },
  de: {
    placeholder: "Fragen Sie nach Ihrer China-Reise...",
    send: "Senden",
    history: "Verlauf",
    newChat: "Neuer Chat",
    savedItineraries: "Gespeicherte Reiserouten",
    noSavedItineraries: "Noch keine gespeicherten Reiserouten",
    mcpOnline: "KI online",
    mcpOffline: "KI offline",
    cancel: "Abbrechen",
    thinking: "Denke nach...",
    saving: "Speichern...",
    map: "Karte",
    saveRoute: "Route speichern",
    signInToSave: "Bitte melden Sie sich an, um Routen zu speichern.",
    noRouteData: "Keine Routendaten zum Speichern.",
    routeSaved: "Route erfolgreich gespeichert!",
    routeSaveFailed: "Speichern der Route fehlgeschlagen: ",
    whereToGo: "Wohin möchten Sie in China reisen?",
    intro:
      "Ich kann Reiserouten planen, Restaurants empfehlen und Alltagsfragen beantworten. Probieren Sie die Schnellvorschläge oder fragen Sie direkt!",
    requestsRemaining: "Noch {n} KI-Anfragen diesen Monat",
    upgrade: "Upgraden",
    monthlyLimitReached:
      "Sie haben Ihr monatliches KI-Limit erreicht. Bitte upgraden Sie, um fortzufahren",
    upgradePlan: "Plan upgraden",
    upgradeToContinue: "Upgraden Sie, um die KI weiter zu nutzen...",
    aiDisclaimer:
      "KI-Antworten dienen nur zur Referenz. Prüfen Sie immer die lokalen Informationen",
    firstUseNotice: "Bei der ersten Nutzung der KI für eine detaillierte Planung sucht und verarbeitet die KI in Echtzeit. Die Wartezeit kann länger sein, in der Regel nicht mehr als 5 Minuten. Bitte haben Sie Geduld.",
    shareItinerary: "Reiseroute teilen",
    shareCode: "Freigabecode:",
    close: "Schließen",
    copyLink: "Link kopieren",
    conversations: "Unterhaltungen",
    itineraries: "Reisepläne",
    newChatButton: "Neuer Chat",
    noConversationsYet: "Noch keine Unterhaltungen",
    justNow: "Gerade eben",
    days: "Tage",
    deleteTitle: "Löschen",
    deleteConfirm: "Diese Unterhaltung löschen?",
    itineraryReady: "Ihre Reiseroute ist fertig - speichern Sie sie, um jederzeit darauf zurückzugreifen.",
    saveItineraryNow: "Diese Reiseroute speichern",
    notNow: "Später",
    saveItineraryTitle: "Reiseroute speichern",
    itineraryName: "Name der Reiseroute",
    savedNotice: "Reiseroute gespeichert!",
    pdfExportFailed: "PDF-Export fehlgeschlagen. Bitte erneut versuchen.",

  },
  ar: {
    placeholder: "اسأل عن رحلتك إلى الصين...",
    send: "إرسال",
    history: "السجل",
    newChat: "محادثة جديدة",
    savedItineraries: "الرحلات المحفوظة",
    noSavedItineraries: "لا توجد رحلات محفوظة بعد",
    mcpOnline: "الذكاء الاصطناعي متصل",
    mcpOffline: "الذكاء الاصطناعي غير متصل",
    cancel: "إلغاء",
    thinking: "جارٍ التفكير...",
    saving: "جارٍ الحفظ...",
    map: "الخريطة",
    saveRoute: "حفظ المسار",
    signInToSave: "يرجى تسجيل الدخول لحفظ المسارات.",
    noRouteData: "لا توجد بيانات مسار للحفظ.",
    routeSaved: "تم حفظ المسار بنجاح!",
    routeSaveFailed: "فشل حفظ المسار: ",
    whereToGo: "إلى أين تريد الذهاب في الصين؟",
    intro:
      "يمكنني مساعدتك في تخطيط الرحلات وتقديم توصيات المطاعم والإجابة عن أسئلة الحياة. جرب الاقتراحات السريعة أو اسأل مباشرة!",
    requestsRemaining: "متبقي {n} طلبات ذكاء اصطناعي هذا الشهر",
    upgrade: "ترقية",
    monthlyLimitReached: "لقد وصلت إلى الحد الشهري لطلبات الذكاء الاصطناعي. قم بالترقية للمتابعة",
    upgradePlan: "ترقية الخطة",
    upgradeToContinue: "قم بالترقية لمواصلة استخدام الذكاء الاصطناعي...",
    aiDisclaimer: "إجابات الذكاء الاصطناعي للرجوع إليها فقط. تحقق دائماً من المعلومات المحلية",
    firstUseNotice: "عند أول استخدام للذكاء الاصطناعي لتخطيط تفاصيل الرحلة، يقوم بالبحث والمعالجة في الوقت الفعلي وقد يستغرق وقتاً أطول، عادة لا يتجاوز 5 دقائق. يرجى الانتظار بصبر.",
    shareItinerary: "مشاركة الرحلة",
    shareCode: "رمز المشاركة:",
    close: "إغلاق",
    copyLink: "نسخ الرابط",
    conversations: "المحادثات",
    itineraries: "مسارات الرحلة",
    newChatButton: "محادثة جديدة",
    noConversationsYet: "لا توجد محادثات بعد",
    justNow: "الآن",
    days: "أيام",
    deleteTitle: "حذف",
    deleteConfirm: "حذف هذه المحادثة؟",
    itineraryReady: "خط سيرك جاهز - احفظه للرجوع إليه في أي وقت.",
    saveItineraryNow: "حفظ خط السير",
    notNow: "ليس الآن",
    saveItineraryTitle: "حفظ خط السير",
    itineraryName: "اسم خط السير",
    savedNotice: "تم حفظ خط السير!",
    pdfExportFailed: "فشل تصدير PDF. يرجى المحاولة مرة أخرى.",

  },
  fa: {
    placeholder: "درباره سفرتان به چین بپرسید...",
    send: "ارسال",
    history: "تاریخچه",
    newChat: "گفتگوی جدید",
    savedItineraries: "مسیرهای ذخیره‌شده",
    noSavedItineraries: "هنوز مسیر ذخیره‌شده‌ای وجود ندارد",
    mcpOnline: "هوش مصنوعی آنلاین",
    mcpOffline: "هوش مصنوعی آفلاین",
    cancel: "لغو",
    thinking: "در حال فکر کردن...",
    saving: "در حال ذخیرهسازی...",
    map: "نقشه",
    saveRoute: "ذخیره مسیر",
    signInToSave: "برای ذخیره مسیر لطفاً وارد شوید.",
    noRouteData: "داده‌ای برای ذخیره مسیر وجود ندارد.",
    routeSaved: "مسیر با موفقیت ذخیره شد!",
    routeSaveFailed: "ذخیره مسیر ناموفق بود: ",
    whereToGo: "کجا در چین می‌خواهید بروید؟",
    intro:
      "می‌توانم به برنامه‌ریزی سفر، پیشنهاد رستوران و پاسخ به سؤالات زندگی کمک کنم. پیشنهادهای سریع را امتحان کنید یا مستقیم بپرسید!",
    requestsRemaining: "{n} درخواست هوش مصنوعی باقی‌مانده در این ماه",
    upgrade: "ارتقا",
    monthlyLimitReached: "به سقف ماهانه درخواست‌های هوش مصنوعی رسیده‌اید. برای ادامه ارتقا دهید",
    upgradePlan: "ارتقای طرح",
    upgradeToContinue: "برای ادامه استفاده از هوش مصنوعی ارتقا دهید...",
    aiDisclaimer: "پاسخ‌های هوش مصنوعی فقط جنبه مرجع دارند. همیشه اطلاعات واقعی محلی را بررسی کنید",
    firstUseNotice: "هنگام اولین استفاده از هوش مصنوعی برای برنامه‌ریزی جزئیات، هوش مصنوعی به صورت زنده جستجو و پردازش می‌کند و ممکن است زمان بیشتری ببرد، معمولاً بیشتر از ۵ دقیقه نیست. لطفاً صبور باشید.",
    shareItinerary: "اشتراک‌گذاری سفر",
    shareCode: "کد اشتراک‌گذاری:",
    close: "بستن",
    copyLink: "کپی لینک",
    conversations: "گفتگوها",
    itineraries: "برنامه سفر",
    newChatButton: "گفتگوی جدید",
    noConversationsYet: "هنوز گفتگویی وجود ندارد",
    justNow: "همین حالا",
    days: "روز",
    deleteTitle: "حذف",
    deleteConfirm: "این گفتگو حذف شود؟",
    itineraryReady: "برنامه سفر شما آماده است - آن را ذخیره کنید تا همیشه در دسترس باشد.",
    saveItineraryNow: "ذخیره این برنامه",
    notNow: "فعلاً نه",
    saveItineraryTitle: "ذخیره برنامه سفر",
    itineraryName: "نام برنامه سفر",
    savedNotice: "برنامه سفر ذخیره شد!",
    pdfExportFailed: "صدور PDF ناموفق بود. لطفاً دوباره تلاش کنید.",

  },
};
