// Generator: builds compact static data files for the Supabase Edge Function `chat`.
// Source data lives in src/data (food, hotels, emergency).
// Requires Node 22.6+ (native TS type-stripping). Run:  node scripts/generate-ai-data.mjs
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const root = process.cwd();
const loadNS = async (rel) => import(pathToFileURL(join(root, rel)).href);

// ---------------------------------------------------------------------------
// 1. Load food data: legacy TS + full per-city JSON datasets
// ---------------------------------------------------------------------------
const foodNS = await loadNS("src/data/food/restaurants.ts");
const citiesFoodNS = await loadNS("src/data/food/cities-food-data.ts");

function compactRestaurant(r, citySlug, cityZh) {
  const coords = r.coordinates || {};
  return {
    id: r.id,
    name: r.name,
    nameEn: r.nameEn,
    type: r.type,
    cuisine: r.cuisine,
    avgPrice: r.avgPrice,
    rating: r.rating,
    address: r.address,
    district: r.district || "",
    city: citySlug || r.city,
    cityZh: cityZh || r.cityZh,
    phone: r.phone,
    hours: r.hours,
    tags: Array.isArray(r.tags) ? r.tags : [],
    lat: r.lat ?? coords.lat ?? undefined,
    lng: r.lng ?? coords.lng ?? undefined,
  };
}

const foodArrays = [];
for (const key of Object.keys(foodNS)) {
  const v = foodNS[key];
  if (Array.isArray(v)) foodArrays.push(v);
}
for (const key of Object.keys(citiesFoodNS)) {
  const v = citiesFoodNS[key];
  if (Array.isArray(v)) foodArrays.push(v);
}
const foodRows = [];
for (const arr of foodArrays) {
  for (const r of arr) {
    if (r && r.name) foodRows.push(compactRestaurant(r));
  }
}

// Full per-city datasets: src/data/cities/*.json -> restaurants[]
const cityFiles = readdirSync(join(root, "src/data/cities"))
  .filter((f) => f.endsWith(".json") && !f.startsWith("index"))
  .sort();
for (const f of cityFiles) {
  const citySlug = f.replace(/\.json$/, "");
  const city = JSON.parse(readFileSync(join(root, "src/data/cities", f), "utf8"));
  const cityZh = city.name || citySlug;
  for (const r of city.restaurants || []) {
    if (r && r.name) foodRows.push(compactRestaurant(r, citySlug, cityZh));
  }
}

const foodById = new Map();
for (const r of foodRows) foodById.set(r.id, r);
const foodData = [...foodById.values()];

// ---------------------------------------------------------------------------
// 2. Load hotel data
// ---------------------------------------------------------------------------
const hotelFiles = readdirSync(join(root, "src/data/hotels"))
  .filter((f) => f.endsWith("-hotels.ts"))
  .sort();
const hotelData = [];
for (const f of hotelFiles) {
  const city = f.replace(/-hotels\.ts$/, "");
  const mod = await loadNS(`src/data/hotels/${f}`);
  const key = `${city}Hotels`;
  const arr = mod[key] ?? [];
  for (const h of arr) {
    if (!h || !h.name) continue;
    hotelData.push({
      id: h.id,
      name: h.name,
      nameEn: h.nameEn,
      category: h.category,
      priceMin: h.priceMin,
      priceMax: h.priceMax,
      city: h.city || city,
      cityZh: h.cityZh,
      district: h.district,
      address: h.address,
      rating: h.rating,
      phone: h.phone,
    });
  }
}

// ---------------------------------------------------------------------------
// 3. Load emergency data
// ---------------------------------------------------------------------------
const emergency = JSON.parse(readFileSync(join(root, "src/data/emergency/city-emergency.json"), "utf8"));
const emergencyData = [];
for (const c of emergency.cities ?? []) {
  emergencyData.push({
    id: c.id,
    name: c.name,
    nameCn: c.nameCn,
    province: c.province,
    police: c.emergencies?.police?.number,
    ambulance: c.emergencies?.ambulance?.number,
    fire: c.emergencies?.fire?.number,
    traffic: c.additionalServices?.traffic,
    info: c.additionalServices?.info,
  });
}

// ---------------------------------------------------------------------------
// 4. Write files
// ---------------------------------------------------------------------------
function writeData(file, name, data) {
  const json = JSON.stringify(data);
  writeFileSync(
    join(root, file),
    `// AUTO-GENERATED by scripts/generate-ai-data.mjs - do not edit by hand\n// Source: src/data (food/hotels/emergency)\nexport const ${name} = ${json};\n`,
    "utf8",
  );
  return json.length;
}

const sizes = {
  food: writeData("supabase/functions/chat/data/food-data.ts", "FOOD_DATA", foodData),
  hotels: writeData("supabase/functions/chat/data/hotel-data.ts", "HOTEL_DATA", hotelData),
  emergency: writeData("supabase/functions/chat/data/emergency-data.ts", "EMERGENCY_DATA", emergencyData),
};

console.log(
  JSON.stringify(
    {
      foodEntries: foodData.length,
      hotelEntries: hotelData.length,
      emergencyEntries: emergencyData.length,
      sizesKB: {
        food: (sizes.food / 1024).toFixed(1),
        hotels: (sizes.hotels / 1024).toFixed(1),
        emergency: (sizes.emergency / 1024).toFixed(1),
      },
    },
    null,
    2,
  ),
);
