const r = await fetch("https://8caa91ae.chinaconnect.pages.dev/");
const t = await r.text();
console.log("Status:", r.status);
console.log("Body len:", t.length);
console.log("Has chinaengage.org:", t.includes("chinaengage.org"));
console.log("Has chinaconnect.io:", t.includes("chinaconnect.io"));
const canonMatch = t.match(/canonical[^>]*?(https?:[^>"']+)/i);
console.log("Canonical:", canonMatch ? canonMatch[1] : "not found");
const ogMatch = t.match(/og:url[^>]*?(https?:[^>"']+)/i);
console.log("OG url:", ogMatch ? ogMatch[1] : "not found");
const hreflangCount = (t.match(/hreflang="[a-z-]+"/g) || []).length;
console.log("Hreflang count:", hreflangCount);
