/**
 * Export labels — 12 languages for itinerary document export (PDF / text).
 * Self-contained (mirrors the chat-labels pattern) so documents always match
 * the user’s UI language.
 */

export type ExportLang =
  | "en"
  | "ja"
  | "ko"
  | "zh-CN"
  | "zh-TW"
  | "th"
  | "vi"
  | "ru"
  | "fr"
  | "de"
  | "ar"
  | "fa";

export interface ExportLabels {
  title: string;
  dest: string;
  days: string;
  highlights: string;
  cost: string;
  tips: string;
  daily: string;
  day: string;
  transport: string;
  duration: string;
  meals: string;
  accommodation: string;
  notes: string;
  tripLength: string;
  originalPlan: string;
  generated: string;
}

export const EXPORT_LABELS: Record<ExportLang, ExportLabels> = {
  en: {
    title: "Travel Itinerary",
    dest: "Destination",
    days: "day(s)",
    highlights: "Highlights",
    cost: "Estimated Total Cost",
    tips: "Travel Tips",
    daily: "Daily Plan",
    day: "Day",
    transport: "Transport",
    duration: "h",
    meals: "Meals",
    accommodation: "Accommodation",
    notes: "Details",
    tripLength: "Duration",
    originalPlan: "Original AI Plan",
    generated: "Generated by ChinaGuide AI — chinaengage.org",
  },
  ja: {
    title: "旅行プラン",
    dest: "目的地",
    days: "日間",
    highlights: "ハイライト",
    cost: "予想総費用",
    tips: "旅行のヒント",
    daily: "日別プラン",
    day: "第",
    transport: "交通",
    duration: "時間",
    meals: "食事",
    accommodation: "宿泊",
    notes: "詳細",
    tripLength: "期間",
    originalPlan: "AIによる元のプラン",
    generated: "ChinaGuide AI によって生成 — chinaengage.org",
  },
  ko: {
    title: "여행 일정",
    dest: "목적지",
    days: "일",
    highlights: "하이라이트",
    cost: "예상 총 비용",
    tips: "여행 팁",
    daily: "일별 일정",
    day: "Day",
    transport: "교통",
    duration: "시간",
    meals: "식사",
    accommodation: "숙소",
    notes: "상세 정보",
    tripLength: "일정 기간",
    originalPlan: "AI 원본 플랜",
    generated: "ChinaGuide AI가 생성함 — chinaengage.org",
  },
  "zh-CN": {
    title: "行程计划",
    dest: "目的地",
    days: "天",
    highlights: "行程亮点",
    cost: "预估总花费",
    tips: "旅行贴士",
    daily: "每日行程",
    day: "第",
    transport: "交通",
    duration: "小时",
    meals: "用餐",
    accommodation: "住宿",
    notes: "详情",
    tripLength: "行程时长",
    originalPlan: "AI 原始规划",
    generated: "由 ChinaGuide AI 生成 — chinaengage.org",
  },
  "zh-TW": {
    title: "行程計畫",
    dest: "目的地",
    days: "天",
    highlights: "行程亮點",
    cost: "預估總花費",
    tips: "旅遊小貼士",
    daily: "每日行程",
    day: "第",
    transport: "交通",
    duration: "小時",
    meals: "用餐",
    accommodation: "住宿",
    notes: "詳情",
    tripLength: "行程時長",
    originalPlan: "AI 原始規劃",
    generated: "由 ChinaGuide AI 產生 — chinaengage.org",
  },
  th: {
    title: "แผนการเดินทาง",
    dest: "ปลายทาง",
    days: "วัน",
    highlights: "ไฮไลท์",
    cost: "ค่าใช้จ่ายโดยประมาณ",
    tips: "เคล็ดลับการเดินทาง",
    daily: "แผนรายวัน",
    day: "วันที่",
    transport: "การเดินทาง",
    duration: "ชม.",
    meals: "อาหาร",
    accommodation: "ที่พัก",
    notes: "รายละเอียด",
    tripLength: "ระยะเวลา",
    originalPlan: "แผน AI ต้นฉบับ",
    generated: "สร้างโดย ChinaGuide AI — chinaengage.org",
  },
  vi: {
    title: "Lịch trình du lịch",
    dest: "Điểm đến",
    days: "ngày",
    highlights: "Điểm nổi bật",
    cost: "Tổng chi phí dự kiến",
    tips: "Mẹo du lịch",
    daily: "Lịch trình hằng ngày",
    day: "Ngày",
    transport: "Di chuyển",
    duration: "giờ",
    meals: "Bữa ăn",
    accommodation: "Chỗ ở",
    notes: "Chi tiết",
    tripLength: "Thời lượng",
    originalPlan: "Kế hoạch gốc của AI",
    generated: "Được tạo bởi ChinaGuide AI — chinaengage.org",
  },
  ru: {
    title: "План путешествия",
    dest: "Направление",
    days: "дн.",
    highlights: "Главное",
    cost: "Предполагаемая стоимость",
    tips: "Советы путешественникам",
    daily: "Ежедневный план",
    day: "День",
    transport: "Транспорт",
    duration: "ч",
    meals: "Питание",
    accommodation: "Проживание",
    notes: "Подробности",
    tripLength: "Продолжительность",
    originalPlan: "Исходный план ИИ",
    generated: "Создано ChinaGuide AI — chinaengage.org",
  },
  fr: {
    title: "Itinéraire de voyage",
    dest: "Destination",
    days: "jour(s)",
    highlights: "Points forts",
    cost: "Coût total estimé",
    tips: "Conseils de voyage",
    daily: "Plan quotidien",
    day: "Jour",
    transport: "Transport",
    duration: "h",
    meals: "Repas",
    accommodation: "Hébergement",
    notes: "Détails",
    tripLength: "Durée",
    originalPlan: "Plan IA original",
    generated: "Généré par ChinaGuide AI — chinaengage.org",
  },
  de: {
    title: "Reiseplan",
    dest: "Reiseziel",
    days: "Tag(e)",
    highlights: "Highlights",
    cost: "Geschätzte Gesamtkosten",
    tips: "Reisetipps",
    daily: "Tagesplan",
    day: "Tag",
    transport: "Transport",
    duration: "Std.",
    meals: "Mahlzeiten",
    accommodation: "Unterkunft",
    notes: "Details",
    tripLength: "Dauer",
    originalPlan: "Original-AI-Plan",
    generated: "Erstellt von ChinaGuide AI — chinaengage.org",
  },
  ar: {
    title: "خطة السفر",
    dest: "الوجهة",
    days: "أيام",
    highlights: "أبرز المعالم",
    cost: "التكلفة الإجمالية التقديرية",
    tips: "نصائح السفر",
    daily: "الخطة اليومية",
    day: "اليوم",
    transport: "المواصلات",
    duration: "ساعة",
    meals: "الوجبات",
    accommodation: "الإقامة",
    notes: "التفاصيل",
    tripLength: "المدة",
    originalPlan: "خطة الذكاء الاصطناعي الأصلية",
    generated: "تم الإنشاء بواسطة ChinaGuide AI — chinaengage.org",
  },
  fa: {
    title: "برنامه سفر",
    dest: "مقصد",
    days: "روز",
    highlights: "برجستهها",
    cost: "هزینه کل تخمینی",
    tips: "نکات سفر",
    daily: "برنامه روزانه",
    day: "روز",
    transport: "حمل و نقل",
    duration: "ساعت",
    meals: "وعدههای غذایی",
    accommodation: "اقامت",
    notes: "جزئیات",
    tripLength: "مدت",
    originalPlan: "برنامه اصلی هوش مصنوعی",
    generated: "ایجاد شده توسط ChinaGuide AI — chinaengage.org",
  },
};

