// Guide component i18n helper.
// - ja: renders the Japanese translation (from JA_GUIDE_OVERRIDES)
// - en: English only (CJK stripped)
// - other langs: per-language override maps (overrides-<lang>.ts); wired in Phase 3
import React from "react";
import { JA_GUIDE_OVERRIDES } from "@/data/guide/ja-overrides";

// Override dictionaries are generated by scripts/translate-guide-strings.mjs.
// Imported lazily via getOverride so pages still build while maps are being generated.
const OVERRIDES: Record<string, Record<string, string>> = {
  ja: JA_GUIDE_OVERRIDES,
};

export function getOverride(lang?: string): Record<string, string> | undefined {
  return lang ? OVERRIDES[lang] : undefined;
}

export function jaText(zh: string | undefined, lang?: string): string {
  if (!zh) return "";
  if (lang === "en") return ""; // English pages must not show Chinese
  const o = getOverride(lang);
  if (o) return o[zh] || zh;
  return zh;
}

// Remove CJK characters from an English/bilingual display string (EN pages).
const CJK_RE = /[\u3400-\u9fff]/;
export function stripZh(s: string): string {
  return s
    .replace(/\s*[（(][^)）]*[\u3400-\u9fff][^)）]*[)）]\s*/g, " ") // "Name (中文)" -> "Name"
    .replace(/\s*\/\s*[\u3400-\u9fff]+/g, "") // "KFC/麦当劳" -> "KFC"
    .replace(/[\u3400-\u9fff]+/g, "") // any remaining CJK chars
    .replace(/\s{2,}/g, " ")
    .trim();
}

// Render an EN/bilingual field for the current language.
// - ja: Japanese override (kept identical to jaText)
// - en: English only (CJK stripped)
// - other langs: per-language override, falling back to English-only
export function guideText(s: string | undefined, lang?: string): string {
  if (!s) return "";
  if (lang === "en") return stripZh(s);
  const o = getOverride(lang);
  if (o) {
    const v = o[s];
    if (v) return v;
  }
  return stripZh(s);
}

// Unified localization for a (EN, ZH) pair: returns the target-language display.
export function localized(en: string | undefined, zh: string | undefined, lang?: string): string {
  if (lang === "en") return stripZh(en || "");
  const o = getOverride(lang);
  if (o) {
    const v = o[zh || ""] || o[en || ""];
    if (v) return v;
  }
  if (lang === "ja" || lang === "zh-CN" || lang === "zh-TW") return zh || stripZh(en || "");
  return stripZh(en || "") || zh || "";
}

export function Bi({ en, zh, lang }: { en: string; zh: string; lang?: string }) {
  return <>{localized(en, zh, lang)}</>;
}

export default Bi;
