import json, sys
sys.stdout.reconfigure(encoding="utf-8")
ja = json.load(open("src/data/cities-i18n/ja/qingdao.json", encoding="utf-8"))
print("ja name:", ja.get("name"))
print("ja climate.type:", ja.get("climate", {}).get("type"))
print("ja climate.tips:", ja.get("climate", {}).get("tips")[:80])
print("ja attractions[0].name:", ja["attractions"][0]["name"])
print("ja attractions[0].ticketPrice:", ja["attractions"][0].get("ticketPrice"))
print("ja attractions[1].name:", ja["attractions"][1]["name"])
ko = json.load(open("src/data/cities-i18n/ko/qingdao.json", encoding="utf-8"))
print()
print("ko name:", ko.get("name"))
print("ko climate.type:", ko.get("climate", {}).get("type"))
print("ko climate.tips:", ko.get("climate", {}).get("tips")[:80])
print("ko attractions[0].name:", ko["attractions"][0]["name"])
print("ko attractions[0].ticketPrice:", ko["attractions"][0].get("ticketPrice"))
